# **Pandas Tutorial**

video from: **Complete Python Pandas Data Science Tutorial! (2025 Updated Edition)** - https://www.youtube.com/watch?v=2uvysYbKdjM

### Часть 1. **Базовые методы и атрибуты**

In [1]:
import pandas as pd

In [2]:
# Названия колонок часто есть по умолчанию во входных файлах
# Названия строк можно тоже не давать. По умолчанию все: 0, 1, 2, ...
df = pd.DataFrame([[1, 2, 3], [4, 5, 6], [7, 8, 9]], columns=["A", "B", "C"], index=["x", "y", "z"])

df.head()  # Вывод первых 5 записей

   A  B  C
x  1  2  3
y  4  5  6
z  7  8  9

In [3]:
df.head(2)  # Вывод первых 2 записей

   A  B  C
x  1  2  3
y  4  5  6

In [4]:
df.tail(2)  # Вывод последних 2 записей

   A  B  C
y  4  5  6
z  7  8  9

In [5]:
df  # Вывод всего фрейма

   A  B  C
x  1  2  3
y  4  5  6
z  7  8  9

In [6]:
df.columns  # Названия колонок; можно с .to_list()

Index(['A', 'B', 'C'], dtype='str')

In [7]:
df.index  # Названия строк

Index(['x', 'y', 'z'], dtype='str')

In [8]:
df.index.to_list()  # Названия строк в виде списка

['x', 'y', 'z']

In [9]:
df.info()

<class 'pandas.DataFrame'>
Index: 3 entries, x to z
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   A       3 non-null      int64
 1   B       3 non-null      int64
 2   C       3 non-null      int64
dtypes: int64(3)
memory usage: 96.0+ bytes

In [10]:
df.describe()  # Информация для каждого столбца
# Количество элементов
# Среднее
# Стандартное отклонение
# Минимальное значение
# и т.д.

         A    B    C
count  3.0  3.0  3.0
mean   4.0  5.0  6.0
std    3.0  3.0  3.0
min    1.0  2.0  3.0
25%    2.5  3.5  4.5
50%    4.0  5.0  6.0
75%    5.5  6.5  7.5
max    7.0  8.0  9.0

In [11]:
df.nunique()  # Количество уникальных элементов в столбцах

A    3
B    3
C    3
dtype: int64

In [12]:
df["A"].unique()  # Уникальные значения для конкретного столбца

array([1, 4, 7])

In [13]:
df.shape  # Форма фрейма: (строк, столбцов)

(3, 3)

In [14]:
df.size  # Количество элементов во фрейме

9

### Часть 2. **Работа с датасетом**

In [15]:
coffee = pd.read_csv("https://raw.githubusercontent.com/KeithGalli/complete-pandas-tutorial/refs/heads/master/warmup-data/coffee.csv")
# coffee = pd.read_csv("data/coffee.csv") - если файл есть в проекте

In [16]:
coffee.head()

         Day Coffee Type  Units Sold
0     Monday    Espresso          25
1     Monday       Latte          15
2    Tuesday    Espresso          30
3    Tuesday       Latte          20
4  Wednesday    Espresso          35

In [17]:
# results = pd.read_feather("data/results.feather")
# results = pd.read_parquet("data/results.parquet")

# results = pd.read_excel("data/olympics-data.xlsx")
# results = pd.read_excel("data/olympics-data.xlsx", sheet_name="results")  # С выбором листа из нескольких таблиц в файле

results = pd.read_csv("data/results.csv")
bios = pd.read_csv("data/bios.csv")
noc_regions = pd.read_csv("data/noc_regions.csv")

In [18]:
results.head()

,year,type,discipline,event,as,athlete_id,noc,team,place,tied,medal
0,1912.0,Summer,Tennis,"Singles, Men (Olympic)",Jean-François Blanchy,1,FRA,NaN,17.0,True,NaN
1,1912.0,Summer,Tennis,"Doubles, Men (Olympic)",Jean-François Blanchy,1,FRA,Jean Montariol,NaN,False,NaN
2,1920.0,Summer,Tennis,"Singles, Men (Olympic)",Jean-François Blanchy,1,FRA,NaN,32.0,True,NaN
3,1920.0,Summer,Tennis,"Doubles, Mixed (Olympic)",Jean-François Blanchy,1,FRA,Jeanne Vaussard,8.0,True,NaN
4,1920.0,Summer,Tennis,"Doubles, Men (Olympic)",Jean-François Blanchy,1,FRA,Jacques Brugnon,4.0,False,NaN

In [19]:
bios.head()

,athlete_id,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date
0,1,Jean-François Blanchy,1886-12-12,Bordeaux,Gironde,FRA,France,NaN,NaN,1960-10-02
1,2,Arnaud Boetsch,1969-04-01,Meulan,Yvelines,FRA,France,183.0,76.0,NaN
2,3,Jean Borotra,1898-08-13,Biarritz,Pyrénées-Atlantiques,FRA,France,183.0,76.0,1994-07-17
3,4,Jacques Brugnon,1895-05-11,Paris VIIIe,Paris,FRA,France,168.0,64.0,1978-03-20
4,5,Albert Canet,1878-04-17,Wandsworth,England,GBR,France,NaN,NaN,1930-07-25

In [20]:
noc_regions.head()

   NOC       region                 notes
0  AFG  Afghanistan                   NaN
1  AHO      Curacao  Netherlands Antilles
2  ALB      Albania                   NaN
3  ALG      Algeria                   NaN
4  AND      Andorra                   NaN

In [21]:
results

,year,type,discipline,event,as,athlete_id,noc,team,place,tied,medal
0,1912.0,Summer,Tennis,"Singles, Men (Olympic)",Jean-François Blanchy,1,FRA,NaN,17.0,True,NaN
1,1912.0,Summer,Tennis,"Doubles, Men (Olympic)",Jean-François Blanchy,1,FRA,Jean Montariol,NaN,False,NaN
2,1920.0,Summer,Tennis,"Singles, Men (Olympic)",Jean-François Blanchy,1,FRA,NaN,32.0,True,NaN
3,1920.0,Summer,Tennis,"Doubles, Mixed (Olympic)",Jean-François Blanchy,1,FRA,Jeanne Vaussard,8.0,True,NaN
4,1920.0,Summer,Tennis,"Doubles, Men (Olympic)",Jean-François Blanchy,1,FRA,Jacques Brugnon,4.0,False,NaN
...,...,...,...,...,...,...,...,...,...,...,...
308403,2022.0,Winter,Luge,"Singles, Men (Olympic)",Marián Skupek,148983,SVK,NaN,26.0,False,NaN
308404,2022.0,Winter,Alpine Skiing (Skiing),"Slalom, Women (Olympic)",Elsa Fermbäck,148984,SWE,NaN,28.0,False,NaN
308405,2022.0,Winter,Alpine Skiing (Skiing),"Team, Mixed (Olympic)",Hilma Lövblom,148985,SWE,Sweden,13.0,False,NaN
308406,2022.0,Winter,Alpine Skiing (Skiing),"Giant Slalom, Women (Olympic)",Hilma Lövblom,148985,SWE,NaN,NaN,False,NaN
308407,2022.0,Winter,NaN,"Slalom, Women (Olympic)",Charlotta Säfvenberg,148986,NaN,NaN,24.0,False,NaN

In [22]:
display(results)  # == results, если редактор не поддерживает более простой синтаксис

,year,type,discipline,event,as,athlete_id,noc,team,place,tied,medal
0,1912.0,Summer,Tennis,"Singles, Men (Olympic)",Jean-François Blanchy,1,FRA,NaN,17.0,True,NaN
1,1912.0,Summer,Tennis,"Doubles, Men (Olympic)",Jean-François Blanchy,1,FRA,Jean Montariol,NaN,False,NaN
2,1920.0,Summer,Tennis,"Singles, Men (Olympic)",Jean-François Blanchy,1,FRA,NaN,32.0,True,NaN
3,1920.0,Summer,Tennis,"Doubles, Mixed (Olympic)",Jean-François Blanchy,1,FRA,Jeanne Vaussard,8.0,True,NaN
4,1920.0,Summer,Tennis,"Doubles, Men (Olympic)",Jean-François Blanchy,1,FRA,Jacques Brugnon,4.0,False,NaN
...,...,...,...,...,...,...,...,...,...,...,...
308403,2022.0,Winter,Luge,"Singles, Men (Olympic)",Marián Skupek,148983,SVK,NaN,26.0,False,NaN
308404,2022.0,Winter,Alpine Skiing (Skiing),"Slalom, Women (Olympic)",Elsa Fermbäck,148984,SWE,NaN,28.0,False,NaN
308405,2022.0,Winter,Alpine Skiing (Skiing),"Team, Mixed (Olympic)",Hilma Lövblom,148985,SWE,Sweden,13.0,False,NaN
308406,2022.0,Winter,Alpine Skiing (Skiing),"Giant Slalom, Women (Olympic)",Hilma Lövblom,148985,SWE,NaN,NaN,False,NaN
308407,2022.0,Winter,NaN,"Slalom, Women (Olympic)",Charlotta Säfvenberg,148986,NaN,NaN,24.0,False,NaN

In [23]:
results.sample()  # Случайная запись. Можно задать количество записей на вывод

,year,type,discipline,event,as,athlete_id,noc,team,place,tied,medal
32146,1920.0,Summer,Hockey,"Hockey, Men (Olympic)",Louis Diercxsens,17666,BEL,Belgium,3.0,False,Bronze

In [24]:
results.sample(4, random_state=15)  # Подобно seed в алгоритмах результат при фиксированном числе будет единственный

,year,type,discipline,event,as,athlete_id,noc,team,place,tied,medal
160715,1952.0,Summer,Athletics,"200 metres, Men (Olympic)",Boonterm Pakpuang,76798,THA,NaN,2.0,False,NaN
56814,1972.0,Summer,Artistic Gymnastics (Gymnastics),"Floor Exercise, Women (Olympic)",Zdena Dorňáková,29120,TCH,NaN,11.0,True,NaN
90068,1972.0,Summer,Shooting,"Running Target, 50 metres, Open (Olympic)",John Kynoch,42350,GBR,NaN,3.0,False,Bronze
93165,1956.0,Summer,Shooting,"Small-Bore Rifle, Prone, 50 metres, Men (Olympic)",César Jayme,43660,PHI,NaN,23.0,False,NaN

### Поподробнее про random_state=

In [25]:
import pandas as pd


df = pd.DataFrame({'A': [1, 2, 3, 4, 5], 'B': [6, 7, 8, 9, 10]})

# Без random_state — результат каждый раз разный
print(df.sample(n=2))

# С random_state=42 — результат всегда одинаковый
print(df.sample(n=2, random_state=42))

   A  B
0  1  6
2  3  8
   A   B
1  2   7
4  5  10

In [26]:
coffee.loc[[]]  # Шапка таблицы
coffee.loc[[1]]  # Шапка таблицы + 1 запись
coffee.loc[[1, 4, 8]]  # Шапка таблицы + конкретные записи

# Срезы
coffee.loc[7:]
coffee.loc[:7]
coffee.loc[5:7]

# Можно выбирать конкретные строки кроме среза для записей
coffee.loc[5:7, "Coffee Type"]
coffee.loc[5:7, ["Day", "Coffee Type"]]
coffee.loc[:, ["Day", "Coffee Type"]]  # Все записи, но конкретные столбцы

coffee.iloc[:, [0, 1]]  # В .iloc[] для выборки столбцов пишем индексы, а не имена

          Day Coffee Type
0      Monday    Espresso
1      Monday       Latte
2     Tuesday    Espresso
3     Tuesday       Latte
4   Wednesday    Espresso
5   Wednesday       Latte
6    Thursday    Espresso
7    Thursday       Latte
8      Friday    Espresso
9      Friday       Latte
10   Saturday    Espresso
11   Saturday       Latte
12     Sunday    Espresso
13     Sunday       Latte

In [27]:
coffee.index = coffee["Day"]  # Сами задаём (переопределяем) индексы для фрейма
coffee.head()

coffee.loc["Monday":"Friday", "Coffee Type"]  # Теперь пользуемся именнованными индексами, в противном случае будет ошибка
coffee.iloc[0:2]  # Тут всё как и было, только в таблицы числовых индексов больше нет

           Day Coffee Type  Units Sold
Day
Monday  Monday    Espresso          25
Monday  Monday       Latte          15

In [28]:
coffee.head()

                 Day Coffee Type  Units Sold
Day
Monday        Monday    Espresso          25
Monday        Monday       Latte          15
Tuesday      Tuesday    Espresso          30
Tuesday      Tuesday       Latte          20
Wednesday  Wednesday    Espresso          35

In [33]:
coffee.loc["Monday", "Units Sold"] = 1  # Меняем значения. Индексы переопределены, поэтому пишем не цифры
coffee.loc["Tuesday":"Wednesday", "Units Sold"] = 5  # Можно пользоваться срезами

In [34]:
coffee.head()

                 Day Coffee Type  Units Sold
Day
Monday        Monday    Espresso         1.0
Monday        Monday       Latte         1.0
Tuesday      Tuesday    Espresso         5.0
Tuesday      Tuesday       Latte         5.0
Wednesday  Wednesday    Espresso         5.0

In [ ]:
# Быстро вывести конкретный элемент. Срезы не допускаются. Аналоги .loc[] и .iloc[]
coffee.at["Monday", "Coffee Type"]
coffee.iat[0, 1]

'Espresso'

In [44]:
coffee["Day"]

Day
Monday          Monday
Monday          Monday
Tuesday        Tuesday
Tuesday        Tuesday
Wednesday    Wednesday
Wednesday    Wednesday
Thursday      Thursday
Thursday      Thursday
Friday          Friday
Friday          Friday
Saturday      Saturday
Saturday      Saturday
Sunday          Sunday
Sunday          Sunday
1                  NaN
Name: Day, dtype: str

In [ ]:
coffee.Day  # Если название столбца - одно слово, можно использовать такой синтаксис

Day
Monday          Monday
Monday          Monday
Tuesday        Tuesday
Tuesday        Tuesday
Wednesday    Wednesday
Wednesday    Wednesday
Thursday      Thursday
Thursday      Thursday
Friday          Friday
Friday          Friday
Saturday      Saturday
Saturday      Saturday
Sunday          Sunday
Sunday          Sunday
1                  NaN
Name: Day, dtype: str

In [ ]:
coffee.sort_values("Units Sold", ascending=False)  # ascending=False - сортировка по убыванию
coffee.sort_values(["Units Sold", "Coffee Type"], ascending=False)  # Сортировка сначала по количеству, потом по названиям
coffee.sort_values(["Units Sold", "Coffee Type"], ascending=[0, 1])  # Алфавитный порядок сортировки

                 Day Coffee Type  Units Sold
Day
Friday        Friday    Espresso        45.0
Saturday    Saturday    Espresso        45.0
Sunday        Sunday    Espresso        45.0
Thursday    Thursday    Espresso        40.0
Friday        Friday       Latte        35.0
Saturday    Saturday       Latte        35.0
Sunday        Sunday       Latte        35.0
Thursday    Thursday       Latte        30.0
Tuesday      Tuesday    Espresso         5.0
Wednesday  Wednesday    Espresso         5.0
Tuesday      Tuesday       Latte         5.0
Wednesday  Wednesday       Latte         5.0
Monday        Monday    Espresso         1.0
Monday        Monday       Latte         1.0
1                NaN         NaN         1.0

In [58]:
for index, row in coffee.iterrows():
    print(index)
    print("\n")
    print(row)  # Можно выводить конкретный элемент: print(row["Units Sold"])
    print("\n\n\n")

Monday


Day              Monday
Coffee Type    Espresso
Units Sold          1.0
Name: Monday, dtype: object




Monday


Day            Monday
Coffee Type     Latte
Units Sold        1.0
Name: Monday, dtype: object




Tuesday


Day             Tuesday
Coffee Type    Espresso
Units Sold          5.0
Name: Tuesday, dtype: object




Tuesday


Day            Tuesday
Coffee Type      Latte
Units Sold         5.0
Name: Tuesday, dtype: object




Wednesday


Day            Wednesday
Coffee Type     Espresso
Units Sold           5.0
Name: Wednesday, dtype: object




Wednesday


Day            Wednesday
Coffee Type        Latte
Units Sold           5.0
Name: Wednesday, dtype: object




Thursday


Day            Thursday
Coffee Type    Espresso
Units Sold         40.0
Name: Thursday, dtype: object




Thursday


Day            Thursday
Coffee Type       Latte
Units Sold         30.0
Name: Thursday, dtype: object




Friday


Day              Friday
Coffee Type    Espresso
Units Sold         45.0
Name: Friday, dtype: object




Friday


Day            Friday
Coffee Type     Latte
Units Sold       35.0
Name: Friday, dtype: object




Saturday


Day            Saturday
Coffee Type    Espresso
Units Sold         45.0
Name: Saturday, dtype: object




Saturday


Day            Saturday
Coffee Type       Latte
Units Sold         35.0
Name: Saturday, dtype: object




Sunday


Day              Sunday
Coffee Type    Espresso
Units Sold         45.0
Name: Sunday, dtype: object




Sunday


Day            Sunday
Coffee Type     Latte
Units Sold       35.0
Name: Sunday, dtype: object




1


Day            NaN
Coffee Type    NaN
Units Sold     1.0
Name: 1, dtype: object

In [59]:
bios.head()

,athlete_id,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date
0,1,Jean-François Blanchy,1886-12-12,Bordeaux,Gironde,FRA,France,NaN,NaN,1960-10-02
1,2,Arnaud Boetsch,1969-04-01,Meulan,Yvelines,FRA,France,183.0,76.0,NaN
2,3,Jean Borotra,1898-08-13,Biarritz,Pyrénées-Atlantiques,FRA,France,183.0,76.0,1994-07-17
3,4,Jacques Brugnon,1895-05-11,Paris VIIIe,Paris,FRA,France,168.0,64.0,1978-03-20
4,5,Albert Canet,1878-04-17,Wandsworth,England,GBR,France,NaN,NaN,1930-07-25

In [60]:
bios.info()

<class 'pandas.DataFrame'>
RangeIndex: 145500 entries, 0 to 145499
Data columns (total 10 columns):
 #   Column        Non-Null Count   Dtype
---  ------        --------------   -----
 0   athlete_id    145500 non-null  int64
 1   name          145500 non-null  str
 2   born_date     143693 non-null  str
 3   born_city     110908 non-null  str
 4   born_region   110908 non-null  str
 5   born_country  110908 non-null  str
 6   NOC           145499 non-null  str
 7   height_cm     106651 non-null  float64
 8   weight_kg     102070 non-null  float64
 9   died_date     33940 non-null   str
dtypes: float64(2), int64(1), str(7)
memory usage: 11.1 MB

In [ ]:
bios = bios.sort_values("height_cm")  # Сортировка
bios.loc[bios["height_cm"] < 150]  # Фильтрация
bios.loc[bios["height_cm"] < 150, ["name", "height_cm"]]  # Сокращённый фрейм
bios.loc[bios["height_cm"] < 150][["name", "height_cm"]]  # Сокращённый метод получения сокращённого фрейма
# bios.sort_index()  # Сортировка по индексам (возвращает к состоянию до сортировки)

                         name  height_cm
4515            Lyton Mphande      127.0
28619         Rosario Briones      127.0
4516            Helman Palije      128.0
4664         Salvador Miranda      130.0
4517           Boston Simbeye      130.0
...                       ...        ...
99398     Yevheniya Filanenko      149.0
128788             Mary Tabal      149.0
66586          Kriscia García      149.0
106054       Alexandra Eremia      149.0
119716  Soniya Chanu Ngangbam      149.0

[372 rows x 2 columns]

In [79]:
# Двойное условие
bios.loc[(bios["height_cm"] < 150) & (bios["born_country"] == "USA")]
bios.loc[(bios["height_cm"] < 150) & (bios["born_country"] == "USA")][:3]  # Применение среза

,athlete_id,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date
114670,115987,Julianne Kirchner,1991-12-19,Florence,Alabama,USA,Marshall Islands,138.0,54.0,NaN
29088,29302,Kim Zmeskal,1976-02-06,Houston,Texas,USA,United States,139.0,36.0,NaN
56566,56969,Joe DePietro,1914-06-10,Paterson,New Jersey,USA,United States,140.0,56.0,1999-03-19

In [81]:
bios["born_country"]

4515      NaN
28619     MEX
4516      NaN
4664      NaN
4517      NaN
         ...
145490    NaN
145491    NaN
145492    CUB
145493    RUS
145499    AUS
Name: born_country, Length: 145500, dtype: str

In [ ]:
bios.loc[bios["born_country"] == "RUS"].count()  # .count() - количество записей в каждом столбце

athlete_id      4276
name            4276
born_date       4276
born_city       4276
born_region     4276
born_country    4276
NOC             4276
height_cm       3599
weight_kg       3488
died_date        852
dtype: int64

In [92]:
bios[bios["name"].str.contains("Yana")]  # Поиск совпадений в столбце имён с учётом регистра
bios[bios["name"].str.contains("yana", case=False)]  # Поиск совпадений в столбце имён без учёта регистра
bios[bios["name"].str.contains("Yana|Nata")]  # Используем синтаксис регулярных выражений
# bios[bios["name"].str.contains("Yana|Nata", regex=False)]  # Поиск с отключенными регулярками

,athlete_id,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date
28222,28434,Natalie Davies,1966-12-01,Farnborough,England,GBR,Great Britain,150.0,47.0,NaN
107060,108180,Nataliya Mikryukova,1983-09-20,NaN,NaN,NaN,Uzbekistan,152.0,49.0,NaN
94146,94907,Natasha Barker,1970-11-30,Sydney,New South Wales,AUS,Australia,153.0,58.0,NaN
100399,101249,Nataliya Ponomaryova,1982-08-13,Yekaterinburg,Sverdlovsk,RUS,Uzbekistan,153.0,NaN,NaN
90507,91230,Natallia Naranovich,1981-08-01,Minsk,Minsk,BLR,Belarus,153.0,42.0,NaN
...,...,...,...,...,...,...,...,...,...,...
144666,148362,Natasha McKay,1995-01-14,Dundee,Scotland,GBR,Great Britain,NaN,NaN,NaN
144875,148580,Yana Khan,2000-09-06,Astana,Astana,KAZ,Kazakhstan,NaN,NaN,NaN
145086,148798,Nataliya Sherina,1999-05-24,Petropavlovsk-Kamchatsky,Kamchatka Kray,RUS,ROC,NaN,NaN,NaN
145159,148876,Natalia Ushkina,1996-09-07,Potma,Respublika Mordoviya,RUS,Romania,NaN,NaN,NaN
145235,148954,Natalie Maag,1997-11-29,Wetzikon,Zürich,SUI,Switzerland,NaN,NaN,NaN

Представим, что в `bios` есть колонки `name`, `email`, `phone`, `bio`.

### 1. Якоря `^` и `$` — привязка к началу/концу строки
```python
# Имена, которые НАЧИНАЮТСЯ с "Dr." (точка экранируется, т.к. в regex . = любой символ)
bios[bios["name"].str.contains(r"^Dr\.", na=False)]

# Биографии, которые ЗАКАНЧИВАЮТСЯ на "PhD"
bios[bios["bio"].str.contains(r"PhD$", na=False)]
```
`^` — начало строки, `$` — конец. Без них `Dr.` нашлось бы и внутри предложения.

### 2. Классы символов и квантификаторы
```python
# Код страны в телефоне: + и 1–3 цифры
bios[bios["phone"].str.contains(r"^\+\d{1,3}\s", na=False)]

# Возраст от 18 до 99 в биографии (две цифры подряд)
bios[bios["bio"].str.contains(r"\b\d{2}\b", na=False)]
```
`\d` — цифра, `{1,3}` — от 1 до 3 повторений, `\b` — граница слова (чтобы "123" не считалось возрастом).

### 3. Валидация email
```python
email_pattern = r"^[\w.+-]+@[\w-]+\.[\w.]+$"
bios[bios["email"].str.contains(email_pattern, na=False)]
```
Разбор: `[\w.+-]+` — один или более символов из букв/цифр/`_`/`.`/`+`/`-`, потом `@`, потом домен, потом точка и TLD.

### 4. Альтернатива с группами — «или» внутри слова
```python
# Имена, содержащие "Ann" или "Anna" (но не "Annabelle")
bios[bios["name"].str.contains(r"\bAnn(a)?\b", na=False)]
```
`(a)?` — необязательная буква `a`, `\b` по краям — чтобы не ловить подстроки.

### 5. Негативный просмотр вперёд — «содержит, НО без ...»
```python
# Все имена, где НЕТ слов "Jr" или "Sr"
bios[bios["name"].str.contains(r"^(?!.*\b(Jr|Sr)\b).*$", na=False)]
```
`(?!...)` — «дальше НЕ должно быть …». Удобно, когда `~str.contains(...)` слишком груб.

### 6. Бонус: `str.extract` — вытащить части в отдельные колонки
Это уже не фильтр, а извлечение — но очень полезно:
```python
# Разделить "Ivanov, Ivan" на фамилию и имя
pattern = r"^(?P<surname>\w+),\s*(?P<first>\w+)$"
bios[["surname", "first"]] = bios["name"].str.extract(pattern)
```
Именованные группы `(?P<name>...)` автоматически становятся названиями колонок.

---

### Пара советов, которые сэкономят нервы:
- **`na=False`** — всегда добавляй в `str.contains`, иначе NaN в колонке даст `NaN` вместо `False`, и фильтрация сломается.
- **`case=False`** — если регистр не важен: `str.contains("anna", case=False)`.
- **`regex=True`** — дефолт в `contains`, но в `str.replace` его нужно явно указывать.
- Используй **raw-строки** `r"..."` — иначе придётся экранировать обратные слеши вдвое: `"\\d+"`.