# **Pandas Tutorial**

video from: **Complete Python Pandas Data Science Tutorial! (2025 Updated Edition)** - https://www.youtube.com/watch?v=2uvysYbKdjM

### Часть 1. **Базовые методы и атрибуты**

In [67]:
import pandas as pd

In [ ]:
# Названия колонок часто есть по умолчанию во входных файлах
# Названия строк можно тоже не давать. По умолчанию все: 0, 1, 2, ...
df = pd.DataFrame([[1, 2, 3], [4, 5, 6], [7, 8, 9]], columns=["A", "B", "C"], index=["x", "y", "z"])

df.head()  # Вывод первых 5 записей

   A  B  C
x  1  2  3
y  4  5  6
z  7  8  9

In [30]:
df.head(2)  # Вывод первых 2 записей

   A  B  C
x  1  2  3
y  4  5  6

In [31]:
df.tail(2)  # Вывод последних 2 записей

   A  B  C
y  4  5  6
z  7  8  9

In [32]:
df  # Вывод всего фрейма

   A  B  C
x  1  2  3
y  4  5  6
z  7  8  9

In [33]:
df.columns  # Названия колонок; можно с .to_list()

Index(['A', 'B', 'C'], dtype='str')

In [34]:
df.index  # Названия строк

Index(['x', 'y', 'z'], dtype='str')

In [35]:
df.index.to_list()  # Названия строк в виде списка

['x', 'y', 'z']

In [36]:
df.info()

<class 'pandas.DataFrame'>
Index: 3 entries, x to z
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   A       3 non-null      int64
 1   B       3 non-null      int64
 2   C       3 non-null      int64
dtypes: int64(3)
memory usage: 96.0+ bytes

In [ ]:
df.describe()  # Информация для каждого столбца
# Количество элементов
# Среднее
# Стандартное отклонение
# Минимальное значение
# и т.д.

         A    B    C
count  3.0  3.0  3.0
mean   4.0  5.0  6.0
std    3.0  3.0  3.0
min    1.0  2.0  3.0
25%    2.5  3.5  4.5
50%    4.0  5.0  6.0
75%    5.5  6.5  7.5
max    7.0  8.0  9.0

In [ ]:
df.nunique()  # Количество уникальных элементов в столбцах

A    3
B    3
C    3
dtype: int64

In [ ]:
df["A"].unique()  # Уникальные значения для конкретного столбца

array([1, 4, 7])

In [47]:
df.shape  # Форма фрейма: (строк, столбцов)

(3, 3)

In [ ]:
df.size  # Количество элементов во фрейме

9

### Часть 2. **Работа с датасетом**

In [52]:
coffee = pd.read_csv("https://raw.githubusercontent.com/KeithGalli/complete-pandas-tutorial/refs/heads/master/warmup-data/coffee.csv")
# coffee = pd.read_csv("data/coffee.csv") - если файл есть в проекте

In [55]:
coffee.head()

         Day Coffee Type  Units Sold
0     Monday    Espresso          25
1     Monday       Latte          15
2    Tuesday    Espresso          30
3    Tuesday       Latte          20
4  Wednesday    Espresso          35

In [84]:
# results = pd.read_feather("data/results.feather")
# results = pd.read_parquet("data/results.parquet")

# results = pd.read_excel("data/olympics-data.xlsx")
# results = pd.read_excel("data/olympics-data.xlsx", sheet_name="results")  # С выбором листа из нескольких таблиц в файле

results = pd.read_csv("data/results.csv")
bios = pd.read_csv("data/bios.csv")
noc_regions = pd.read_csv("data/noc_regions.csv")

In [87]:
results.head()

,year,type,discipline,event,as,athlete_id,noc,team,place,tied,medal
0,1912.0,Summer,Tennis,"Singles, Men (Olympic)",Jean-François Blanchy,1,FRA,NaN,17.0,True,NaN
1,1912.0,Summer,Tennis,"Doubles, Men (Olympic)",Jean-François Blanchy,1,FRA,Jean Montariol,NaN,False,NaN
2,1920.0,Summer,Tennis,"Singles, Men (Olympic)",Jean-François Blanchy,1,FRA,NaN,32.0,True,NaN
3,1920.0,Summer,Tennis,"Doubles, Mixed (Olympic)",Jean-François Blanchy,1,FRA,Jeanne Vaussard,8.0,True,NaN
4,1920.0,Summer,Tennis,"Doubles, Men (Olympic)",Jean-François Blanchy,1,FRA,Jacques Brugnon,4.0,False,NaN

In [88]:
bios.head()

,athlete_id,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date
0,1,Jean-François Blanchy,1886-12-12,Bordeaux,Gironde,FRA,France,NaN,NaN,1960-10-02
1,2,Arnaud Boetsch,1969-04-01,Meulan,Yvelines,FRA,France,183.0,76.0,NaN
2,3,Jean Borotra,1898-08-13,Biarritz,Pyrénées-Atlantiques,FRA,France,183.0,76.0,1994-07-17
3,4,Jacques Brugnon,1895-05-11,Paris VIIIe,Paris,FRA,France,168.0,64.0,1978-03-20
4,5,Albert Canet,1878-04-17,Wandsworth,England,GBR,France,NaN,NaN,1930-07-25

In [89]:
noc_regions.head()

   NOC       region                 notes
0  AFG  Afghanistan                   NaN
1  AHO      Curacao  Netherlands Antilles
2  ALB      Albania                   NaN
3  ALG      Algeria                   NaN
4  AND      Andorra                   NaN

In [97]:
results

,year,type,discipline,event,as,athlete_id,noc,team,place,tied,medal
0,1912.0,Summer,Tennis,"Singles, Men (Olympic)",Jean-François Blanchy,1,FRA,NaN,17.0,True,NaN
1,1912.0,Summer,Tennis,"Doubles, Men (Olympic)",Jean-François Blanchy,1,FRA,Jean Montariol,NaN,False,NaN
2,1920.0,Summer,Tennis,"Singles, Men (Olympic)",Jean-François Blanchy,1,FRA,NaN,32.0,True,NaN
3,1920.0,Summer,Tennis,"Doubles, Mixed (Olympic)",Jean-François Blanchy,1,FRA,Jeanne Vaussard,8.0,True,NaN
4,1920.0,Summer,Tennis,"Doubles, Men (Olympic)",Jean-François Blanchy,1,FRA,Jacques Brugnon,4.0,False,NaN
...,...,...,...,...,...,...,...,...,...,...,...
308403,2022.0,Winter,Luge,"Singles, Men (Olympic)",Marián Skupek,148983,SVK,NaN,26.0,False,NaN
308404,2022.0,Winter,Alpine Skiing (Skiing),"Slalom, Women (Olympic)",Elsa Fermbäck,148984,SWE,NaN,28.0,False,NaN
308405,2022.0,Winter,Alpine Skiing (Skiing),"Team, Mixed (Olympic)",Hilma Lövblom,148985,SWE,Sweden,13.0,False,NaN
308406,2022.0,Winter,Alpine Skiing (Skiing),"Giant Slalom, Women (Olympic)",Hilma Lövblom,148985,SWE,NaN,NaN,False,NaN
308407,2022.0,Winter,NaN,"Slalom, Women (Olympic)",Charlotta Säfvenberg,148986,NaN,NaN,24.0,False,NaN

In [96]:
display(results)  # == results, если редактор не поддерживает более простой синтаксис

,year,type,discipline,event,as,athlete_id,noc,team,place,tied,medal
0,1912.0,Summer,Tennis,"Singles, Men (Olympic)",Jean-François Blanchy,1,FRA,NaN,17.0,True,NaN
1,1912.0,Summer,Tennis,"Doubles, Men (Olympic)",Jean-François Blanchy,1,FRA,Jean Montariol,NaN,False,NaN
2,1920.0,Summer,Tennis,"Singles, Men (Olympic)",Jean-François Blanchy,1,FRA,NaN,32.0,True,NaN
3,1920.0,Summer,Tennis,"Doubles, Mixed (Olympic)",Jean-François Blanchy,1,FRA,Jeanne Vaussard,8.0,True,NaN
4,1920.0,Summer,Tennis,"Doubles, Men (Olympic)",Jean-François Blanchy,1,FRA,Jacques Brugnon,4.0,False,NaN
...,...,...,...,...,...,...,...,...,...,...,...
308403,2022.0,Winter,Luge,"Singles, Men (Olympic)",Marián Skupek,148983,SVK,NaN,26.0,False,NaN
308404,2022.0,Winter,Alpine Skiing (Skiing),"Slalom, Women (Olympic)",Elsa Fermbäck,148984,SWE,NaN,28.0,False,NaN
308405,2022.0,Winter,Alpine Skiing (Skiing),"Team, Mixed (Olympic)",Hilma Lövblom,148985,SWE,Sweden,13.0,False,NaN
308406,2022.0,Winter,Alpine Skiing (Skiing),"Giant Slalom, Women (Olympic)",Hilma Lövblom,148985,SWE,NaN,NaN,False,NaN
308407,2022.0,Winter,NaN,"Slalom, Women (Olympic)",Charlotta Säfvenberg,148986,NaN,NaN,24.0,False,NaN

In [ ]:
results.sample()  # Случайная запись. Можно задать количество записей на вывод

,year,type,discipline,event,as,athlete_id,noc,team,place,tied,medal
238316,2010.0,Winter,Alpine Skiing (Skiing),"Downhill, Men (Olympic)",Ivan Ratkić,110103,CRO,NaN,41.0,False,NaN

In [136]:
results.sample(4, random_state=15)  # Подобно seed в алгоритмах результат при фиксированном числе будет единственный

,year,type,discipline,event,as,athlete_id,noc,team,place,tied,medal
160715,1952.0,Summer,Athletics,"200 metres, Men (Olympic)",Boonterm Pakpuang,76798,THA,NaN,2.0,False,NaN
56814,1972.0,Summer,Artistic Gymnastics (Gymnastics),"Floor Exercise, Women (Olympic)",Zdena Dorňáková,29120,TCH,NaN,11.0,True,NaN
90068,1972.0,Summer,Shooting,"Running Target, 50 metres, Open (Olympic)",John Kynoch,42350,GBR,NaN,3.0,False,Bronze
93165,1956.0,Summer,Shooting,"Small-Bore Rifle, Prone, 50 metres, Men (Olympic)",César Jayme,43660,PHI,NaN,23.0,False,NaN

### Поподробнее про random_state=

In [129]:
import pandas as pd


df = pd.DataFrame({'A': [1, 2, 3, 4, 5], 'B': [6, 7, 8, 9, 10]})

# Без random_state — результат каждый раз разный
print(df.sample(n=2))

# С random_state=42 — результат всегда одинаковый
print(df.sample(n=2, random_state=42))

   A  B
0  1  6
1  2  7
   A   B
1  2   7
4  5  10

In [ ]:
coffee.loc[[]]  # Шапка таблицы
coffee.loc[[1]]  # Шапка таблицы + 1 запись
coffee.loc[[1, 4, 8]]  # Шапка таблицы + конкретные записи

# Срезы
coffee.loc[7:]
coffee.loc[:7]
coffee.loc[5:7]

# Можно выбирать конкретные строки кроме среза для записей
coffee.loc[5:7, "Coffee Type"]
coffee.loc[5:7, ["Day", "Coffee Type"]]
coffee.loc[:, ["Day", "Coffee Type"]]  # Все записи, но конкретные столбцы

coffee.iloc[:, [0, 1]]  # В .iloc[] для выборки столбцов пишем индексы, а не имена

          Day Coffee Type
0      Monday    Espresso
1      Monday       Latte
2     Tuesday    Espresso
3     Tuesday       Latte
4   Wednesday    Espresso
5   Wednesday       Latte
6    Thursday    Espresso
7    Thursday       Latte
8      Friday    Espresso
9      Friday       Latte
10   Saturday    Espresso
11   Saturday       Latte
12     Sunday    Espresso
13     Sunday       Latte

In [ ]:
coffee.index = coffee["Day"]  # Сами задаём (переопределяем) индексы для фрейма
coffee.head()

coffee.loc["Monday":"Friday", "Coffee Type"]  # Теперь пользуемся именнованными индексами, в противном случае будет ошибка
coffee.iloc[0:2]  # Тут всё как и было, только в таблицы числовых индексов больше нет

           Day Coffee Type  Units Sold
Day
Monday  Monday    Espresso          25
Monday  Monday       Latte          15