# **Pandas Tutorial**

video from: **Complete Python Pandas Data Science Tutorial! (2025 Updated Edition)** - https://www.youtube.com/watch?v=2uvysYbKdjM

### Часть 1. **Базовые методы и атрибуты**

In [1]:
import pandas as pd

In [2]:
# Названия колонок часто есть по умолчанию во входных файлах
# Названия строк можно тоже не давать. По умолчанию все: 0, 1, 2, ...
df = pd.DataFrame([[1, 2, 3], [4, 5, 6], [7, 8, 9]], columns=["A", "B", "C"], index=["x", "y", "z"])

df.head()  # Вывод первых 5 записей

   A  B  C
x  1  2  3
y  4  5  6
z  7  8  9

In [3]:
df.head(2)  # Вывод первых 2 записей

   A  B  C
x  1  2  3
y  4  5  6

In [4]:
df.tail(2)  # Вывод последних 2 записей

   A  B  C
y  4  5  6
z  7  8  9

In [5]:
df  # Вывод всего фрейма

   A  B  C
x  1  2  3
y  4  5  6
z  7  8  9

In [6]:
df.columns  # Названия колонок; можно с .to_list()

Index(['A', 'B', 'C'], dtype='str')

In [7]:
df.index  # Названия строк

Index(['x', 'y', 'z'], dtype='str')

In [8]:
df.index.to_list()  # Названия строк в виде списка

['x', 'y', 'z']

In [9]:
df.info()

<class 'pandas.DataFrame'>
Index: 3 entries, x to z
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   A       3 non-null      int64
 1   B       3 non-null      int64
 2   C       3 non-null      int64
dtypes: int64(3)
memory usage: 96.0+ bytes

In [10]:
df.describe()  # Информация для каждого столбца
# Количество элементов
# Среднее
# Стандартное отклонение
# Минимальное значение
# и т.д.

         A    B    C
count  3.0  3.0  3.0
mean   4.0  5.0  6.0
std    3.0  3.0  3.0
min    1.0  2.0  3.0
25%    2.5  3.5  4.5
50%    4.0  5.0  6.0
75%    5.5  6.5  7.5
max    7.0  8.0  9.0

In [11]:
df.nunique()  # Количество уникальных элементов в столбцах

A    3
B    3
C    3
dtype: int64

In [12]:
df["A"].unique()  # Уникальные значения для конкретного столбца

array([1, 4, 7])

In [13]:
df.shape  # Форма фрейма: (строк, столбцов)

(3, 3)

In [14]:
df.size  # Количество элементов во фрейме

9

### Часть 2. **Работа с датасетом**

In [15]:
coffee = pd.read_csv("https://raw.githubusercontent.com/KeithGalli/complete-pandas-tutorial/refs/heads/master/warmup-data/coffee.csv")
# coffee = pd.read_csv("data/coffee.csv") - если файл есть в проекте

In [16]:
coffee.head()

         Day Coffee Type  Units Sold
0     Monday    Espresso          25
1     Monday       Latte          15
2    Tuesday    Espresso          30
3    Tuesday       Latte          20
4  Wednesday    Espresso          35

In [17]:
# results = pd.read_feather("data/results.feather")
# results = pd.read_parquet("data/results.parquet")

# results = pd.read_excel("data/olympics-data.xlsx")
# results = pd.read_excel("data/olympics-data.xlsx", sheet_name="results")  # С выбором листа из нескольких таблиц в файле

results = pd.read_csv("data/results.csv")
bios = pd.read_csv("data/bios.csv")
noc_regions = pd.read_csv("data/noc_regions.csv")

In [18]:
results.head()

,year,type,discipline,event,as,athlete_id,noc,team,place,tied,medal
0,1912.0,Summer,Tennis,"Singles, Men (Olympic)",Jean-François Blanchy,1,FRA,NaN,17.0,True,NaN
1,1912.0,Summer,Tennis,"Doubles, Men (Olympic)",Jean-François Blanchy,1,FRA,Jean Montariol,NaN,False,NaN
2,1920.0,Summer,Tennis,"Singles, Men (Olympic)",Jean-François Blanchy,1,FRA,NaN,32.0,True,NaN
3,1920.0,Summer,Tennis,"Doubles, Mixed (Olympic)",Jean-François Blanchy,1,FRA,Jeanne Vaussard,8.0,True,NaN
4,1920.0,Summer,Tennis,"Doubles, Men (Olympic)",Jean-François Blanchy,1,FRA,Jacques Brugnon,4.0,False,NaN

In [19]:
bios.head()

,athlete_id,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date
0,1,Jean-François Blanchy,1886-12-12,Bordeaux,Gironde,FRA,France,NaN,NaN,1960-10-02
1,2,Arnaud Boetsch,1969-04-01,Meulan,Yvelines,FRA,France,183.0,76.0,NaN
2,3,Jean Borotra,1898-08-13,Biarritz,Pyrénées-Atlantiques,FRA,France,183.0,76.0,1994-07-17
3,4,Jacques Brugnon,1895-05-11,Paris VIIIe,Paris,FRA,France,168.0,64.0,1978-03-20
4,5,Albert Canet,1878-04-17,Wandsworth,England,GBR,France,NaN,NaN,1930-07-25

In [20]:
noc_regions.head()

   NOC       region                 notes
0  AFG  Afghanistan                   NaN
1  AHO      Curacao  Netherlands Antilles
2  ALB      Albania                   NaN
3  ALG      Algeria                   NaN
4  AND      Andorra                   NaN

In [21]:
results

,year,type,discipline,event,as,athlete_id,noc,team,place,tied,medal
0,1912.0,Summer,Tennis,"Singles, Men (Olympic)",Jean-François Blanchy,1,FRA,NaN,17.0,True,NaN
1,1912.0,Summer,Tennis,"Doubles, Men (Olympic)",Jean-François Blanchy,1,FRA,Jean Montariol,NaN,False,NaN
2,1920.0,Summer,Tennis,"Singles, Men (Olympic)",Jean-François Blanchy,1,FRA,NaN,32.0,True,NaN
3,1920.0,Summer,Tennis,"Doubles, Mixed (Olympic)",Jean-François Blanchy,1,FRA,Jeanne Vaussard,8.0,True,NaN
4,1920.0,Summer,Tennis,"Doubles, Men (Olympic)",Jean-François Blanchy,1,FRA,Jacques Brugnon,4.0,False,NaN
...,...,...,...,...,...,...,...,...,...,...,...
308403,2022.0,Winter,Luge,"Singles, Men (Olympic)",Marián Skupek,148983,SVK,NaN,26.0,False,NaN
308404,2022.0,Winter,Alpine Skiing (Skiing),"Slalom, Women (Olympic)",Elsa Fermbäck,148984,SWE,NaN,28.0,False,NaN
308405,2022.0,Winter,Alpine Skiing (Skiing),"Team, Mixed (Olympic)",Hilma Lövblom,148985,SWE,Sweden,13.0,False,NaN
308406,2022.0,Winter,Alpine Skiing (Skiing),"Giant Slalom, Women (Olympic)",Hilma Lövblom,148985,SWE,NaN,NaN,False,NaN
308407,2022.0,Winter,NaN,"Slalom, Women (Olympic)",Charlotta Säfvenberg,148986,NaN,NaN,24.0,False,NaN

In [22]:
display(results)  # == results, если редактор не поддерживает более простой синтаксис

,year,type,discipline,event,as,athlete_id,noc,team,place,tied,medal
0,1912.0,Summer,Tennis,"Singles, Men (Olympic)",Jean-François Blanchy,1,FRA,NaN,17.0,True,NaN
1,1912.0,Summer,Tennis,"Doubles, Men (Olympic)",Jean-François Blanchy,1,FRA,Jean Montariol,NaN,False,NaN
2,1920.0,Summer,Tennis,"Singles, Men (Olympic)",Jean-François Blanchy,1,FRA,NaN,32.0,True,NaN
3,1920.0,Summer,Tennis,"Doubles, Mixed (Olympic)",Jean-François Blanchy,1,FRA,Jeanne Vaussard,8.0,True,NaN
4,1920.0,Summer,Tennis,"Doubles, Men (Olympic)",Jean-François Blanchy,1,FRA,Jacques Brugnon,4.0,False,NaN
...,...,...,...,...,...,...,...,...,...,...,...
308403,2022.0,Winter,Luge,"Singles, Men (Olympic)",Marián Skupek,148983,SVK,NaN,26.0,False,NaN
308404,2022.0,Winter,Alpine Skiing (Skiing),"Slalom, Women (Olympic)",Elsa Fermbäck,148984,SWE,NaN,28.0,False,NaN
308405,2022.0,Winter,Alpine Skiing (Skiing),"Team, Mixed (Olympic)",Hilma Lövblom,148985,SWE,Sweden,13.0,False,NaN
308406,2022.0,Winter,Alpine Skiing (Skiing),"Giant Slalom, Women (Olympic)",Hilma Lövblom,148985,SWE,NaN,NaN,False,NaN
308407,2022.0,Winter,NaN,"Slalom, Women (Olympic)",Charlotta Säfvenberg,148986,NaN,NaN,24.0,False,NaN

In [23]:
results.sample()  # Случайная запись. Можно задать количество записей на вывод

,year,type,discipline,event,as,athlete_id,noc,team,place,tied,medal
96823,1984.0,Summer,Swimming (Aquatics),"100 metres Butterfly, Women (Olympic)",Janet Tibbits,45133,AUS,NaN,6.0,False,NaN

In [24]:
results.sample(4, random_state=15)  # Подобно seed в алгоритмах результат при фиксированном числе будет единственный

,year,type,discipline,event,as,athlete_id,noc,team,place,tied,medal
160715,1952.0,Summer,Athletics,"200 metres, Men (Olympic)",Boonterm Pakpuang,76798,THA,NaN,2.0,False,NaN
56814,1972.0,Summer,Artistic Gymnastics (Gymnastics),"Floor Exercise, Women (Olympic)",Zdena Dorňáková,29120,TCH,NaN,11.0,True,NaN
90068,1972.0,Summer,Shooting,"Running Target, 50 metres, Open (Olympic)",John Kynoch,42350,GBR,NaN,3.0,False,Bronze
93165,1956.0,Summer,Shooting,"Small-Bore Rifle, Prone, 50 metres, Men (Olympic)",César Jayme,43660,PHI,NaN,23.0,False,NaN

### Поподробнее про random_state=

In [25]:
import pandas as pd


df = pd.DataFrame({'A': [1, 2, 3, 4, 5], 'B': [6, 7, 8, 9, 10]})

# Без random_state — результат каждый раз разный
print(df.sample(n=2))

# С random_state=42 — результат всегда одинаковый
print(df.sample(n=2, random_state=42))

   A  B
3  4  9
0  1  6
   A   B
1  2   7
4  5  10

In [26]:
coffee.loc[[]]  # Шапка таблицы
coffee.loc[[1]]  # Шапка таблицы + 1 запись
coffee.loc[[1, 4, 8]]  # Шапка таблицы + конкретные записи

# Срезы
coffee.loc[7:]
coffee.loc[:7]
coffee.loc[5:7]

# Можно выбирать конкретные строки и столбцы
coffee.loc[5:7, "Coffee Type"]
coffee.loc[5:7, ["Day", "Coffee Type"]]
coffee.loc[:, ["Day", "Coffee Type"]]  # Все записи, но конкретные столбцы

coffee.iloc[:, [0, 1]]  # В .iloc[] для выборки столбцов пишем индексы, а не имена

          Day Coffee Type
0      Monday    Espresso
1      Monday       Latte
2     Tuesday    Espresso
3     Tuesday       Latte
4   Wednesday    Espresso
5   Wednesday       Latte
6    Thursday    Espresso
7    Thursday       Latte
8      Friday    Espresso
9      Friday       Latte
10   Saturday    Espresso
11   Saturday       Latte
12     Sunday    Espresso
13     Sunday       Latte

In [27]:
coffee.index = coffee["Day"]  # Сами задаём (переопределяем) индексы для фрейма
coffee.head()

coffee.loc["Monday":"Friday", "Coffee Type"]  # Теперь пользуемся именнованными индексами, в противном случае будет ошибка
coffee.iloc[0:2]  # Тут всё как и было, только в таблицы числовых индексов больше нет

           Day Coffee Type  Units Sold
Day
Monday  Monday    Espresso          25
Monday  Monday       Latte          15

In [28]:
coffee.head()

                 Day Coffee Type  Units Sold
Day
Monday        Monday    Espresso          25
Monday        Monday       Latte          15
Tuesday      Tuesday    Espresso          30
Tuesday      Tuesday       Latte          20
Wednesday  Wednesday    Espresso          35

In [29]:
coffee.loc["Monday", "Units Sold"] = 1  # Меняем значения. Индексы переопределены, поэтому пишем не цифры
coffee.loc["Tuesday":"Wednesday", "Units Sold"] = 5  # Можно пользоваться срезами

In [30]:
coffee.head()

                 Day Coffee Type  Units Sold
Day
Monday        Monday    Espresso           1
Monday        Monday       Latte           1
Tuesday      Tuesday    Espresso           5
Tuesday      Tuesday       Latte           5
Wednesday  Wednesday    Espresso           5

In [31]:
# Быстро вывести конкретный элемент. Срезы не допускаются. Аналоги .loc[] и .iloc[]
coffee.at["Monday", "Coffee Type"]
coffee.iat[0, 1]

'Espresso'

In [32]:
coffee["Day"]

Day
Monday          Monday
Monday          Monday
Tuesday        Tuesday
Tuesday        Tuesday
Wednesday    Wednesday
Wednesday    Wednesday
Thursday      Thursday
Thursday      Thursday
Friday          Friday
Friday          Friday
Saturday      Saturday
Saturday      Saturday
Sunday          Sunday
Sunday          Sunday
Name: Day, dtype: str

In [33]:
coffee.Day  # Если название столбца - одно слово, можно использовать такой синтаксис

Day
Monday          Monday
Monday          Monday
Tuesday        Tuesday
Tuesday        Tuesday
Wednesday    Wednesday
Wednesday    Wednesday
Thursday      Thursday
Thursday      Thursday
Friday          Friday
Friday          Friday
Saturday      Saturday
Saturday      Saturday
Sunday          Sunday
Sunday          Sunday
Name: Day, dtype: str

In [34]:
coffee.sort_values("Units Sold", ascending=False)  # ascending=False - сортировка по убыванию
coffee.sort_values(["Units Sold", "Coffee Type"], ascending=False)  # Сортировка сначала по количеству, потом по названиям
coffee.sort_values(["Units Sold", "Coffee Type"], ascending=[0, 1])  # Алфавитный порядок сортировки

                 Day Coffee Type  Units Sold
Day
Friday        Friday    Espresso          45
Saturday    Saturday    Espresso          45
Sunday        Sunday    Espresso          45
Thursday    Thursday    Espresso          40
Friday        Friday       Latte          35
Saturday    Saturday       Latte          35
Sunday        Sunday       Latte          35
Thursday    Thursday       Latte          30
Tuesday      Tuesday    Espresso           5
Wednesday  Wednesday    Espresso           5
Tuesday      Tuesday       Latte           5
Wednesday  Wednesday       Latte           5
Monday        Monday    Espresso           1
Monday        Monday       Latte           1

In [35]:
for index, row in coffee.iterrows():
    print(index)
    print("\n")
    print(row)  # Можно выводить конкретный элемент: print(row["Units Sold"])
    print("\n\n\n")

Monday


Day              Monday
Coffee Type    Espresso
Units Sold            1
Name: Monday, dtype: object




Monday


Day            Monday
Coffee Type     Latte
Units Sold          1
Name: Monday, dtype: object




Tuesday


Day             Tuesday
Coffee Type    Espresso
Units Sold            5
Name: Tuesday, dtype: object




Tuesday


Day            Tuesday
Coffee Type      Latte
Units Sold           5
Name: Tuesday, dtype: object




Wednesday


Day            Wednesday
Coffee Type     Espresso
Units Sold             5
Name: Wednesday, dtype: object




Wednesday


Day            Wednesday
Coffee Type        Latte
Units Sold             5
Name: Wednesday, dtype: object




Thursday


Day            Thursday
Coffee Type    Espresso
Units Sold           40
Name: Thursday, dtype: object




Thursday


Day            Thursday
Coffee Type       Latte
Units Sold           30
Name: Thursday, dtype: object




Friday


Day              Friday
Coffee Type    Espresso
Units Sold           45
Name: Friday, dtype: object




Friday


Day            Friday
Coffee Type     Latte
Units Sold         35
Name: Friday, dtype: object




Saturday


Day            Saturday
Coffee Type    Espresso
Units Sold           45
Name: Saturday, dtype: object




Saturday


Day            Saturday
Coffee Type       Latte
Units Sold           35
Name: Saturday, dtype: object




Sunday


Day              Sunday
Coffee Type    Espresso
Units Sold           45
Name: Sunday, dtype: object




Sunday


Day            Sunday
Coffee Type     Latte
Units Sold         35
Name: Sunday, dtype: object

In [36]:
bios.head()

,athlete_id,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date
0,1,Jean-François Blanchy,1886-12-12,Bordeaux,Gironde,FRA,France,NaN,NaN,1960-10-02
1,2,Arnaud Boetsch,1969-04-01,Meulan,Yvelines,FRA,France,183.0,76.0,NaN
2,3,Jean Borotra,1898-08-13,Biarritz,Pyrénées-Atlantiques,FRA,France,183.0,76.0,1994-07-17
3,4,Jacques Brugnon,1895-05-11,Paris VIIIe,Paris,FRA,France,168.0,64.0,1978-03-20
4,5,Albert Canet,1878-04-17,Wandsworth,England,GBR,France,NaN,NaN,1930-07-25

In [37]:
bios.info()

<class 'pandas.DataFrame'>
RangeIndex: 145500 entries, 0 to 145499
Data columns (total 10 columns):
 #   Column        Non-Null Count   Dtype
---  ------        --------------   -----
 0   athlete_id    145500 non-null  int64
 1   name          145500 non-null  str
 2   born_date     143693 non-null  str
 3   born_city     110908 non-null  str
 4   born_region   110908 non-null  str
 5   born_country  110908 non-null  str
 6   NOC           145499 non-null  str
 7   height_cm     106651 non-null  float64
 8   weight_kg     102070 non-null  float64
 9   died_date     33940 non-null   str
dtypes: float64(2), int64(1), str(7)
memory usage: 11.1 MB

In [38]:
bios = bios.sort_values("height_cm")  # Сортировка
bios.loc[bios["height_cm"] < 150]  # Фильтрация
bios.loc[bios["height_cm"] < 150, ["name", "height_cm"]]  # Сокращённый фрейм
bios.loc[bios["height_cm"] < 150][["name", "height_cm"]]  # Другой метод получения сокращённого фрейма
# bios.sort_index()  # Сортировка по индексам (возвращает к состоянию до сортировки)

                         name  height_cm
4515            Lyton Mphande      127.0
28619         Rosario Briones      127.0
4516            Helman Palije      128.0
4664         Salvador Miranda      130.0
4517           Boston Simbeye      130.0
...                       ...        ...
99398     Yevheniya Filanenko      149.0
128788             Mary Tabal      149.0
66586          Kriscia García      149.0
106054       Alexandra Eremia      149.0
119716  Soniya Chanu Ngangbam      149.0

[372 rows x 2 columns]

In [39]:
# Двойное условие
bios.loc[(bios["height_cm"] < 150) & (bios["born_country"] == "USA")]
bios.loc[(bios["height_cm"] < 150) & (bios["born_country"] == "USA")][:3]  # Применение среза

,athlete_id,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date
114670,115987,Julianne Kirchner,1991-12-19,Florence,Alabama,USA,Marshall Islands,138.0,54.0,NaN
29088,29302,Kim Zmeskal,1976-02-06,Houston,Texas,USA,United States,139.0,36.0,NaN
56566,56969,Joe DePietro,1914-06-10,Paterson,New Jersey,USA,United States,140.0,56.0,1999-03-19

In [40]:
bios["born_country"]

4515      NaN
28619     MEX
4516      NaN
4664      NaN
4517      NaN
         ...
145490    NaN
145491    NaN
145492    CUB
145493    RUS
145499    AUS
Name: born_country, Length: 145500, dtype: str

In [41]:
bios.loc[bios["born_country"] == "RUS"].count()  # .count() - количество записей в каждом столбце

athlete_id      4276
name            4276
born_date       4276
born_city       4276
born_region     4276
born_country    4276
NOC             4276
height_cm       3599
weight_kg       3488
died_date        852
dtype: int64

In [42]:
bios[bios["name"].str.contains("Yana")]  # Поиск совпадений в столбце имён с учётом регистра
bios[bios["name"].str.contains("yana", case=False)]  # Поиск совпадений в столбце имён без учёта регистра
bios[bios["name"].str.contains("Yana|Nata")]  # Используем синтаксис регулярных выражений
# bios[bios["name"].str.contains("Yana|Nata", regex=False)]  # Поиск с отключенными регулярками

,athlete_id,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date
28222,28434,Natalie Davies,1966-12-01,Farnborough,England,GBR,Great Britain,150.0,47.0,NaN
107060,108180,Nataliya Mikryukova,1983-09-20,NaN,NaN,NaN,Uzbekistan,152.0,49.0,NaN
94146,94907,Natasha Barker,1970-11-30,Sydney,New South Wales,AUS,Australia,153.0,58.0,NaN
100399,101249,Nataliya Ponomaryova,1982-08-13,Yekaterinburg,Sverdlovsk,RUS,Uzbekistan,153.0,NaN,NaN
90507,91230,Natallia Naranovich,1981-08-01,Minsk,Minsk,BLR,Belarus,153.0,42.0,NaN
...,...,...,...,...,...,...,...,...,...,...
144666,148362,Natasha McKay,1995-01-14,Dundee,Scotland,GBR,Great Britain,NaN,NaN,NaN
144875,148580,Yana Khan,2000-09-06,Astana,Astana,KAZ,Kazakhstan,NaN,NaN,NaN
145086,148798,Nataliya Sherina,1999-05-24,Petropavlovsk-Kamchatsky,Kamchatka Kray,RUS,ROC,NaN,NaN,NaN
145159,148876,Natalia Ushkina,1996-09-07,Potma,Respublika Mordoviya,RUS,Romania,NaN,NaN,NaN
145235,148954,Natalie Maag,1997-11-29,Wetzikon,Zürich,SUI,Switzerland,NaN,NaN,NaN

Представим, что в `bios` есть колонки `name`, `email`, `phone`, `bio`.

### 1. Якоря `^` и `$` — привязка к началу/концу строки
```python
# Имена, которые НАЧИНАЮТСЯ с "Dr." (точка экранируется, т.к. в regex . = любой символ)
bios[bios["name"].str.contains(r"^Dr\.", na=False)]

# Биографии, которые ЗАКАНЧИВАЮТСЯ на "PhD"
bios[bios["bio"].str.contains(r"PhD$", na=False)]
```
`^` — начало строки, `$` — конец. Без них `Dr.` нашлось бы и внутри предложения.

### 2. Классы символов и квантификаторы
```python
# Код страны в телефоне: + и 1–3 цифры
bios[bios["phone"].str.contains(r"^\+\d{1,3}\s", na=False)]

# Возраст от 18 до 99 в биографии (две цифры подряд)
bios[bios["bio"].str.contains(r"\b\d{2}\b", na=False)]
```
`\d` — цифра, `{1,3}` — от 1 до 3 повторений, `\b` — граница слова (чтобы "123" не считалось возрастом).

### 3. Валидация email
```python
email_pattern = r"^[\w.+-]+@[\w-]+\.[\w.]+$"
bios[bios["email"].str.contains(email_pattern, na=False)]
```
Разбор: `[\w.+-]+` — один или более символов из букв/цифр/`_`/`.`/`+`/`-`, потом `@`, потом домен, потом точка и TLD.

### 4. Альтернатива с группами — «или» внутри слова
```python
# Имена, содержащие "Ann" или "Anna" (но не "Annabelle")
bios[bios["name"].str.contains(r"\bAnn(a)?\b", na=False)]
```
`(a)?` — необязательная буква `a`, `\b` по краям — чтобы не ловить подстроки.

### 5. Негативный просмотр вперёд — «содержит, НО без ...»
```python
# Все имена, где НЕТ слов "Jr" или "Sr"
bios[bios["name"].str.contains(r"^(?!.*\b(Jr|Sr)\b).*$", na=False)]
```
`(?!...)` — «дальше НЕ должно быть …». Удобно, когда `~str.contains(...)` слишком груб.

### 6. Бонус: `str.extract` — вытащить части в отдельные колонки
Это уже не фильтр, а извлечение — но очень полезно:
```python
# Разделить "Ivanov, Ivan" на фамилию и имя
pattern = r"^(?P<surname>\w+),\s*(?P<first>\w+)$"
bios[["surname", "first"]] = bios["name"].str.extract(pattern)
```
Именованные группы `(?P<name>...)` автоматически становятся названиями колонок.

---

### Пара советов, которые сэкономят нервы:
- **`na=False`** — всегда добавляй в `str.contains`, иначе NaN в колонке даст `NaN` вместо `False`, и фильтрация сломается.
- **`case=False`** — если регистр не важен: `str.contains("anna", case=False)`.
- **`regex=True`** — дефолт в `contains`, но в `str.replace` его нужно явно указывать.
- Используй **raw-строки** `r"..."` — иначе придётся экранировать обратные слеши вдвое: `"\\d+"`.

In [43]:
bios[bios["born_country"].isin(["USA", "FRA", "GBR"]) & (bios["name"].str.startswith("Andrew"))]  # Комбинируем условия
# | - логическое ИЛИ
# .isin() - проверка столбца на наличие в нём точных совпадений с условием
# .startswith() - проверка на начало строки

,athlete_id,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date
89145,89857,Andrew Kooner,1979-03-11,Kettering,England,GBR,Canada,165.0,54.0,NaN
29915,30141,Andrew Morris,1961-11-30,Swansea,Wales,GBR,Great Britain,168.0,65.0,NaN
120710,122658,Andrew Selby,1988-12-25,Barry,Wales,GBR,Great Britain,169.0,NaN,NaN
116896,118320,Andrew Weibrecht,1986-02-10,Saranac Lake,New York,USA,United States,170.0,86.0,NaN
125429,127774,Andrew Matthews,1984-10-26,Slough,England,GBR,Great Britain,172.0,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...
62305,62768,Andrew Libano,1903-01-19,New Orleans,Louisiana,USA,United States,NaN,NaN,1935-06-22
97123,97906,Andrew Stroukoff,1950-04-27,Trenton,New Jersey,USA,United States,NaN,NaN,NaN
98703,99499,Andrew Freshwater,1973-05-31,Grantown-on-Spey,Scotland,GBR,Great Britain,NaN,NaN,NaN
139361,142832,Andrew Albicy,1990-03-21,Sèvres,Hauts-de-Seine,FRA,France,NaN,NaN,NaN
145437,149160,Andrew Blaser,1989-05-08,Meridian,Idaho,USA,United States,NaN,NaN,NaN

In [44]:
bios.query("born_country == \"USA\"")  # Ещё один способ фильтрации по условию
bios.query('born_country == "USA" and born_city == "Seattle"') # От кавычек зависит надобность в "\"

,athlete_id,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date
129572,132191,Morghan King,1985-10-08,Seattle,Washington,USA,United States,153.0,48.0,NaN
29079,29293,Joyce Tanac,1950-09-27,Seattle,Washington,USA,United States,156.0,49.0,NaN
77214,77805,Gail Devers,1966-11-19,Seattle,Washington,USA,United States,160.0,55.0,NaN
80807,81458,Cindy Kauffman,1948-08-23,Seattle,Washington,USA,United States,160.0,49.0,NaN
50802,51161,Nancy Ramey,1940-06-29,Seattle,Washington,USA,United States,160.0,51.0,NaN
...,...,...,...,...,...,...,...,...,...,...
85678,86360,"Ray Hadley, Jr.",1943-10-06,Seattle,Washington,USA,United States,NaN,NaN,1961-02-15
95265,96035,Ralf Olin,1925-04-12,Seattle,Washington,USA,Canada,NaN,NaN,2007-05-25
135448,138662,Maude Davis Crossland,2003-03-19,Seattle,Washington,USA,Colombia,NaN,NaN,NaN
136993,140229,Jenell Berhorst,2003-12-13,Seattle,Washington,USA,United States,NaN,NaN,NaN
145446,149169,Corinne Stoddard,2001-08-15,Seattle,Washington,USA,United States,NaN,NaN,NaN

In [45]:
coffee["price"] = 4.99  # Создание и заполнение нового столбца один значением

In [46]:
import numpy as np

In [47]:
coffee["new_price"] = np.where(coffee["Coffee Type"]=="Espresso", 3.99, 5.99)  # Создание нового столбца с выбором заполнения

In [48]:
coffee.drop(columns=["price"], inplace=True)  # Удаление столбца
# Используем inplace=False для автоматического изменения фрейма. Решает проблему, похожую на необходимость перезаписывать строку после изменения: text = text.replace()

In [49]:
coffee.head()

                 Day Coffee Type  Units Sold  new_price
Day
Monday        Monday    Espresso           1       3.99
Monday        Monday       Latte           1       5.99
Tuesday      Tuesday    Espresso           5       3.99
Tuesday      Tuesday       Latte           5       5.99
Wednesday  Wednesday    Espresso           5       3.99

In [50]:
coffee_new = coffee  # Неправильное копирование фрейма! Оба элемента ссылаются на один и тот же объект в памяти, из-за чего фреймы одинаковые, хотя изменения вносятся только в один фрейм
coffee_new["price"] = 4.99

coffee_new

                 Day Coffee Type  Units Sold  new_price  price
Day
Monday        Monday    Espresso           1       3.99   4.99
Monday        Monday       Latte           1       5.99   4.99
Tuesday      Tuesday    Espresso           5       3.99   4.99
Tuesday      Tuesday       Latte           5       5.99   4.99
Wednesday  Wednesday    Espresso           5       3.99   4.99
Wednesday  Wednesday       Latte           5       5.99   4.99
Thursday    Thursday    Espresso          40       3.99   4.99
Thursday    Thursday       Latte          30       5.99   4.99
Friday        Friday    Espresso          45       3.99   4.99
Friday        Friday       Latte          35       5.99   4.99
Saturday    Saturday    Espresso          45       3.99   4.99
Saturday    Saturday       Latte          35       5.99   4.99
Sunday        Sunday    Espresso          45       3.99   4.99
Sunday        Sunday       Latte          35       5.99   4.99

In [51]:
coffee

                 Day Coffee Type  Units Sold  new_price  price
Day
Monday        Monday    Espresso           1       3.99   4.99
Monday        Monday       Latte           1       5.99   4.99
Tuesday      Tuesday    Espresso           5       3.99   4.99
Tuesday      Tuesday       Latte           5       5.99   4.99
Wednesday  Wednesday    Espresso           5       3.99   4.99
Wednesday  Wednesday       Latte           5       5.99   4.99
Thursday    Thursday    Espresso          40       3.99   4.99
Thursday    Thursday       Latte          30       5.99   4.99
Friday        Friday    Espresso          45       3.99   4.99
Friday        Friday       Latte          35       5.99   4.99
Saturday    Saturday    Espresso          45       3.99   4.99
Saturday    Saturday       Latte          35       5.99   4.99
Sunday        Sunday    Espresso          45       3.99   4.99
Sunday        Sunday       Latte          35       5.99   4.99

In [52]:
coffee_new = coffee.copy()  # Правильное копирование
coffee_new["year"] = 2026

In [53]:
coffee

                 Day Coffee Type  Units Sold  new_price  price
Day
Monday        Monday    Espresso           1       3.99   4.99
Monday        Monday       Latte           1       5.99   4.99
Tuesday      Tuesday    Espresso           5       3.99   4.99
Tuesday      Tuesday       Latte           5       5.99   4.99
Wednesday  Wednesday    Espresso           5       3.99   4.99
Wednesday  Wednesday       Latte           5       5.99   4.99
Thursday    Thursday    Espresso          40       3.99   4.99
Thursday    Thursday       Latte          30       5.99   4.99
Friday        Friday    Espresso          45       3.99   4.99
Friday        Friday       Latte          35       5.99   4.99
Saturday    Saturday    Espresso          45       3.99   4.99
Saturday    Saturday       Latte          35       5.99   4.99
Sunday        Sunday    Espresso          45       3.99   4.99
Sunday        Sunday       Latte          35       5.99   4.99

In [54]:
coffee_new

                 Day Coffee Type  Units Sold  new_price  price  year
Day
Monday        Monday    Espresso           1       3.99   4.99  2026
Monday        Monday       Latte           1       5.99   4.99  2026
Tuesday      Tuesday    Espresso           5       3.99   4.99  2026
Tuesday      Tuesday       Latte           5       5.99   4.99  2026
Wednesday  Wednesday    Espresso           5       3.99   4.99  2026
Wednesday  Wednesday       Latte           5       5.99   4.99  2026
Thursday    Thursday    Espresso          40       3.99   4.99  2026
Thursday    Thursday       Latte          30       5.99   4.99  2026
Friday        Friday    Espresso          45       3.99   4.99  2026
Friday        Friday       Latte          35       5.99   4.99  2026
Saturday    Saturday    Espresso          45       3.99   4.99  2026
Saturday    Saturday       Latte          35       5.99   4.99  2026
Sunday        Sunday    Espresso          45       3.99   4.99  2026
Sunday        Sunday       Latte          35       5.99   4.99  2026

In [55]:
coffee = coffee[["Day", "Coffee Type", "Units Sold", "new_price"]]  # Ещё способ выбрать или скопировать фрейм с конкретными столбцами

In [56]:
coffee["revenue"] = coffee["Units Sold"] * coffee["new_price"]  # Добавление стобца выручки

In [57]:
coffee.rename(columns={"new_price": "price"}, inplace=True)  # Переименование столбца

In [58]:
coffee.head()

                 Day Coffee Type  Units Sold  price  revenue
Day
Monday        Monday    Espresso           1   3.99     3.99
Monday        Monday       Latte           1   5.99     5.99
Tuesday      Tuesday    Espresso           5   3.99    19.95
Tuesday      Tuesday       Latte           5   5.99    29.95
Wednesday  Wednesday    Espresso           5   3.99    19.95

In [59]:
bios_new = bios.copy()

In [60]:
bios_new["first_name"] = bios_new["name"].str.split().str[0]  # Создание нового столбца из первого слова в ячейке "name"

In [61]:
bios_new.head()

,athlete_id,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date,first_name
4515,4530,Lyton Mphande,1963-05-14,NaN,NaN,NaN,Malawi,127.0,62.0,NaN,Lyton
28619,28832,Rosario Briones,1953-10-05,San Luis Potosí,San Luis Potosí,MEX,Mexico,127.0,42.0,NaN,Rosario
4516,4531,Helman Palije,1967-06-24,NaN,NaN,NaN,Malawi,128.0,74.0,NaN,Helman
4664,4681,Salvador Miranda,1949-09-13,NaN,NaN,NaN,Nicaragua,130.0,51.0,NaN,Salvador
4517,4532,Boston Simbeye,1959-12-24,NaN,NaN,NaN,Malawi,130.0,67.0,NaN,Boston

In [62]:
bios_new.info()

<class 'pandas.DataFrame'>
Index: 145500 entries, 4515 to 145499
Data columns (total 11 columns):
 #   Column        Non-Null Count   Dtype
---  ------        --------------   -----
 0   athlete_id    145500 non-null  int64
 1   name          145500 non-null  str
 2   born_date     143693 non-null  str
 3   born_city     110908 non-null  str
 4   born_region   110908 non-null  str
 5   born_country  110908 non-null  str
 6   NOC           145499 non-null  str
 7   height_cm     106651 non-null  float64
 8   weight_kg     102070 non-null  float64
 9   died_date     33940 non-null   str
 10  first_name    145500 non-null  object
dtypes: float64(2), int64(1), object(1), str(7)
memory usage: 13.3+ MB

In [63]:
bios_new["born_datetime"] = pd.to_datetime(bios_new["born_date"])  # Создаём новый столбец и задаём ему тип данных datetime
# bios_new["born_datetime"] = pd.to_datetime(bios_new["born_date"], format="%Y-%m-%d")  # Можно явно задать формат даты
# bios_new["born_datetime"] = pd.to_datetime(bios_new["born_date"], errors="coerce")  # Преобразование данных для верной работы с форматами даты

In [64]:
bios_new.head()

,athlete_id,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date,first_name,born_datetime
4515,4530,Lyton Mphande,1963-05-14,NaN,NaN,NaN,Malawi,127.0,62.0,NaN,Lyton,1963-05-14
28619,28832,Rosario Briones,1953-10-05,San Luis Potosí,San Luis Potosí,MEX,Mexico,127.0,42.0,NaN,Rosario,1953-10-05
4516,4531,Helman Palije,1967-06-24,NaN,NaN,NaN,Malawi,128.0,74.0,NaN,Helman,1967-06-24
4664,4681,Salvador Miranda,1949-09-13,NaN,NaN,NaN,Nicaragua,130.0,51.0,NaN,Salvador,1949-09-13
4517,4532,Boston Simbeye,1959-12-24,NaN,NaN,NaN,Malawi,130.0,67.0,NaN,Boston,1959-12-24

In [65]:
bios_new.info()

<class 'pandas.DataFrame'>
Index: 145500 entries, 4515 to 145499
Data columns (total 12 columns):
 #   Column         Non-Null Count   Dtype
---  ------         --------------   -----
 0   athlete_id     145500 non-null  int64
 1   name           145500 non-null  str
 2   born_date      143693 non-null  str
 3   born_city      110908 non-null  str
 4   born_region    110908 non-null  str
 5   born_country   110908 non-null  str
 6   NOC            145499 non-null  str
 7   height_cm      106651 non-null  float64
 8   weight_kg      102070 non-null  float64
 9   died_date      33940 non-null   str
 10  first_name     145500 non-null  object
 11  born_datetime  143693 non-null  datetime64[us]
dtypes: datetime64[us](1), float64(2), int64(1), object(1), str(7)
memory usage: 14.4+ MB

In [66]:
bios_new["born_year"] = bios_new["born_datetime"].dt.year  # С помощью типа данных datetime можем обратиться к году и создать новый столбец
bios_new["is_leap_year"] = bios_new["born_datetime"].dt.is_leap_year  # Можно добавить флаг високосного года

bios_new[["name", "born_year", "is_leap_year"]]

                         name  born_year  is_leap_year
4515            Lyton Mphande     1963.0         False
28619         Rosario Briones     1953.0         False
4516            Helman Palije     1967.0         False
4664         Salvador Miranda     1949.0         False
4517           Boston Simbeye     1959.0         False
...                       ...        ...           ...
145490            Sin Ye-Chan     1995.0         False
145491          Matthew Wepke     1989.0         False
145492  Carlos García-Ordóñez     1927.0         False
145493     Landysh Falyakhova     1998.0         False
145499          Bill Phillips     1913.0         False

[145500 rows x 3 columns]

Шпаргалка по форматам даты: https://www.bairesdev.com/tools/strftime/?__cf_chl_f_tk=hwktMs.nEQyGiMJTkcXHERyFhdzfYqZlaCtUqCF7vCY-1783415293-1.0.1.1-5WStowqWwc87BhQcgYiM09fHmTGui2J8_0DAnf3NUog

In [67]:
bios_new.to_csv("data/bios_new.csv", index=False)  # Сохранение обновлённого фрейма в файл, где индексы не добавлены