# Гайд: https://www.youtube.com/watch?v=JUH3UdOxgB0

## **`Series`**

In [1]:
import pandas as pd

In [2]:
salaries = pd.Series([60.0, 45.0, 50.0])  # Колонка зарплат в тысячах рублей
print(salaries)

0    60.0
1    45.0
2    50.0
dtype: float64

In [3]:
salaries = pd.Series([60.0, 45.0, 50.0], ["Маша", "Паша", "Женя"])  # Добавляем свои индексы
print(salaries)

Маша    60.0
Паша    45.0
Женя    50.0
dtype: float64

In [4]:
salaries = pd.Series({"Маша": 60.0, "Паша": 45.0, "Женя": 50.0})  # Можно передавать словарь
salaries  # Аналогично print(salaries)

Маша    60.0
Паша    45.0
Женя    50.0
dtype: float64

In [5]:
print(salaries.values)

[60. 45. 50.]

In [6]:
salaries.values

array([60., 45., 50.])

In [7]:
salaries.index  # Аналогично print(salaries.index)

Index(['Маша', 'Паша', 'Женя'], dtype='str')

In [8]:
salaries.values.tolist()

[60.0, 45.0, 50.0]

In [9]:
salaries.index.tolist()

['Маша', 'Паша', 'Женя']

In [10]:
salaries.to_dict()  # Словарь, где ключи - индексы

{'Маша': 60.0, 'Паша': 45.0, 'Женя': 50.0}

In [11]:
print(salaries.loc["Женя"])  # Зарпалата Жени (можно без print, но будет больше служебной информации)

50.0

In [12]:
salaries.loc["Паша"] = 55.0  # Изменяем значение
salaries.loc["Саша"] = 65.0  # Добавляем новую запись
salaries

Маша    60.0
Паша    55.0
Женя    50.0
Саша    65.0
dtype: float64

In [13]:
salaries.loc["Маша":"Паша"]  # В отличие от обычных срезов, конечный элемент включается в выборку

Маша    60.0
Паша    55.0
dtype: float64

In [14]:
salaries.loc["Паша":"Женя"] = [55.0, 60.0]  #  Можем менять сразу несколько значений
salaries

Маша    60.0
Паша    55.0
Женя    60.0
Саша    65.0
dtype: float64

In [15]:
for name, salary in salaries.items():
    print(f"{name} получает {salary} тысяч рублей.")

Маша получает 60.0 тысяч рублей.
Паша получает 55.0 тысяч рублей.
Женя получает 60.0 тысяч рублей.
Саша получает 65.0 тысяч рублей.

In [16]:
salaries + 5  # Увеличиваем все зарплаты на 5 тысяч рублей

Маша    65.0
Паша    60.0
Женя    65.0
Саша    70.0
dtype: float64

In [17]:
salaries = pd.Series([60.0, 45.0, 50.0], ["Маша", "Паша", "Женя"])
bonuses = pd.Series([5.0, 1.0, 3.0], ["Паша", "Маша", "Женя"])
salaries + bonuses  # Добавим первональные премии к зарплатам

Женя    53.0
Маша    61.0
Паша    50.0
dtype: float64

In [18]:
# Если явно не указать индексы, они автоматические проставятся и операция останется корректной
a = pd.Series([1, 2, 3])
b = pd.Series([4, 5, 6])
a + b

0    5
1    7
2    9
dtype: int64

In [19]:
c = (a + b) ** 2  # Если результат нужно сохранить, присваиваем ему переменную
c

0    25
1    49
2    81
dtype: int64

In [20]:
a *= b  # Оператор составного присвоения тоже работает
a

0     4
1    10
2    18
dtype: int64

In [21]:
salaries > 55

Маша     True
Паша    False
Женя    False
dtype: bool

In [22]:
bonuses_2023 = pd.Series([5.0, 1.0, 3.0], ["Паша", "Маша", "Женя"])
bonuses_2024 = pd.Series([7.0, 0.5, 4.0], ["Паша", "Маша", "Женя"])
bonuses_2024 > bonuses_2023

Паша     True
Маша    False
Женя     True
dtype: bool

In [23]:
(bonuses_2024 > bonuses_2023) & (bonuses_2024 > 1)  # Комбинируем условия

Паша     True
Маша    False
Женя     True
dtype: bool

In [24]:
index = [True, False, True]
salaries[index]  # Булевская индексация

Маша    60.0
Женя    50.0
dtype: float64

In [25]:
# index = salaries < 55
# salaries[index]

salaries[salaries < 55]  # Лучше одной строкой

Паша    45.0
Женя    50.0
dtype: float64

In [26]:
salaries[salaries < 55] += 5.0
salaries

Маша    60.0
Паша    50.0
Женя    55.0
dtype: float64

In [27]:
# Если индексы не совпадают, то появляется NaN
a = pd.Series([1, 2, 3], ["A", "B", "C"])
b = pd.Series([4, 5, 6], ["A", "B", "X"])
c = a + b
c

A    5.0
B    7.0
C    NaN
X    NaN
dtype: float64

In [28]:
# Если длины разные, видим похожую картину
a = pd.Series([1, 2, 3], ["A", "B", "C"])
b = pd.Series([4, 5], ["A", "B"])
c = a + b
c

A    5.0
B    7.0
C    NaN
dtype: float64

In [29]:
c.loc["C"] is None  # NaN != None

False

In [30]:
c.isna()

A    False
B    False
C     True
dtype: bool

In [31]:
c.notna()

# Можем избавиться от нанов с помощью булевской индексации
# c = c[c.notna()] или c = c.dropna()
# c

A     True
B     True
C    False
dtype: bool

In [32]:
c[c.isna()] = 0  # Заполняем наны нулями или c = c.fillna(0)
c

A    5.0
B    7.0
C    0.0
dtype: float64

In [33]:
salaries.min()

np.float64(50.0)

In [34]:
salaries.max()

np.float64(60.0)

In [35]:
salaries.sum()

np.float64(165.0)

In [36]:
salaries.mean()

np.float64(55.0)

In [37]:
salaries *= 1.33
salaries = salaries.round()  # округление до целого
# salaries = salaries.round(10)  # округление до десятых
# salariessalaries = salaries.round(100)  # округление до сотых
salaries

Маша    80.0
Паша    66.0
Женя    73.0
dtype: float64

In [38]:
salaries.std()

np.float64(7.0)

In [39]:
salaries.median()

np.float64(73.0)

In [40]:
salaries  = salaries.reindex(["Маша", "Миша"])
salaries

Маша    80.0
Миша     NaN
dtype: float64

In [41]:
salaries  = salaries.reindex(["Маша", "Женя"])
salaries

Маша    80.0
Женя     NaN
dtype: float64

In [42]:
def increase_salary(x: float) -> float:
    if x < 50:
        return x * 1.1
    if x < 60:
        return x * 1.05
    return x


salaries = pd.Series([60, 45, 50], ["Маша", "Паша", "Женя"])
salaries = salaries.map(increase_salary)
salaries

Маша    60.0
Паша    49.5
Женя    52.5
dtype: float64

## Задача 1. Зарплаты и премии

Нужно посчитать зарплаты с учётом премий и на сколько в среднем они увеличились. Округлить до 500 рублей

In [43]:
salaries = pd.Series([60, 45, 50], ["Маша", "Паша", "Женя"])
bonuses = pd.Series({"Маша": 2, "Женя": 7})  # % от зарплаты

In [44]:
money = salaries * (1 + bonuses / 100)  # Добавляем премии

In [45]:
money.fillna(salaries, inplace=True)  # Кому не дали премии, для того берём старое значение

Женя    53.5
Маша    61.2
Паша    45.0
dtype: float64

In [46]:
money

Женя    53.5
Маша    61.2
Паша    45.0
dtype: float64

In [47]:
(money - salaries).mean()  # Среднее значение прибавки зарплат

np.float64(1.5666666666666675)

In [48]:
money

Женя    53.5
Маша    61.2
Паша    45.0
dtype: float64

### Решение автора туториала

In [49]:
salaries = pd.Series([60.0, 45.0, 50.0], ["Маша", "Паша", "Женя"])
bonuses = pd.Series({"Маша": 2.0, "Женя": 7.0})  # (% от зарплаты)

In [50]:
bonuses = bonuses.reindex(salaries.index).fillna(0)
new_salaries = salaries * (1 + bonuses / 100)

In [51]:
new_salaries

Маша    61.2
Паша    45.0
Женя    53.5
dtype: float64

In [52]:
new_salaries.mean() - salaries.mean()

np.float64(1.5666666666666629)

## **`DataFrame`**

In [53]:
employee = pd.DataFrame(
    {"Зарплата": [60, 45, 50], "Возраст": [26, 45, 30]}
)
employee

   Зарплата  Возраст
0        60       26
1        45       45
2        50       30

In [54]:
employee = pd.DataFrame(
    {"Зарплата": [60, 45, 50], "Возраст": [26, 45, 30]},
    ["Маша", "Паша", "Женя"]  # Укажем индексы
)
employee

      Зарплата  Возраст
Маша        60       26
Паша        45       45
Женя        50       30

In [55]:
employee.values

array([[60, 26],
       [45, 45],
       [50, 30]])

In [56]:
employee.index

Index(['Маша', 'Паша', 'Женя'], dtype='str')

In [57]:
employee.columns

Index(['Зарплата', 'Возраст'], dtype='str')

In [58]:
employee["Зарплата"]  # Выбираем конкретный series

Маша    60
Паша    45
Женя    50
Name: Зарплата, dtype: int64

In [59]:
employee.loc["Маша"]  # Выбираем данные по индексу

Зарплата    60
Возраст     26
Name: Маша, dtype: int64

In [60]:
employee.loc["Маша":"Паша"]  # Используем срез и получаем DataFrame

      Зарплата  Возраст
Маша        60       26
Паша        45       45

In [61]:
employee.loc["Маша", "Зарплата"]

np.int64(60)

In [62]:
employee.loc["Маша", "Зарплата"] = 65
employee

      Зарплата  Возраст
Маша        65       26
Паша        45       45
Женя        50       30

In [63]:
employee.loc["Саша"] = pd.Series({"Зарплата": 40, "Возраст": 20})  # Создаём новую запись
employee

      Зарплата  Возраст
Маша        65       26
Паша        45       45
Женя        50       30
Саша        40       20

In [64]:
employee["Возраст"] = [26, 46, 31, 20]  # Меняем значения списком, важно знать последовательность
employee

      Зарплата  Возраст
Маша        65       26
Паша        45       46
Женя        50       31
Саша        40       20

In [65]:
employee["Отдел"] = "Продажи"
employee

      Зарплата  Возраст    Отдел
Маша        65       26  Продажи
Паша        45       46  Продажи
Женя        50       31  Продажи
Саша        40       20  Продажи

In [66]:
bonuses = pd.Series([5, 1, 3, 2], ["Маша", "Паша", "Женя", "Саша"])
employee["Зарплата"] + bonuses  # Сохранения не будет, нужно присвоение

Маша    70
Паша    46
Женя    53
Саша    42
dtype: int64

In [67]:
employee["Юбилей"] = employee["Возраст"] % 10 == 0
employee

      Зарплата  Возраст    Отдел  Юбилей
Маша        65       26  Продажи   False
Паша        45       46  Продажи   False
Женя        50       31  Продажи   False
Саша        40       20  Продажи    True

In [68]:
employee[employee["Зарплата"] < 55]

      Зарплата  Возраст    Отдел  Юбилей
Паша        45       46  Продажи   False
Женя        50       31  Продажи   False
Саша        40       20  Продажи    True

In [69]:
employee = employee.drop(index=["Женя"])
employee

      Зарплата  Возраст    Отдел  Юбилей
Маша        65       26  Продажи   False
Паша        45       46  Продажи   False
Саша        40       20  Продажи    True

In [70]:
employee = employee.drop(columns=["Юбилей"])
employee

      Зарплата  Возраст    Отдел
Маша        65       26  Продажи
Паша        45       46  Продажи
Саша        40       20  Продажи

In [71]:
employee = employee.rename(index={"Маша": "Mary", "Паша": "Paul", "Саша": "Sasha"})
employee = employee.rename(columns={"Зарплата": "Salary", "Возраст": "Age"})
employee

       Salary  Age    Отдел
Mary       65   26  Продажи
Paul       45   46  Продажи
Sasha      40   20  Продажи

In [72]:
employee["Age"].mean()

np.float64(30.666666666666668)

In [73]:
employee.describe()
# количество колонок не равных нан
# среднее
# стандартное отклонение
# минимум
# 3 квартиля
# максимум

          Salary        Age
count   3.000000   3.000000
mean   50.000000  30.666667
std    13.228757  13.613719
min    40.000000  20.000000
25%    42.500000  23.000000
50%    45.000000  26.000000
75%    55.000000  36.000000
max    65.000000  46.000000

In [74]:
employee[["Salary", "Age"]].corr()  # Коэффициенты корреляция Пирсона между колонками
# 1 - положительная зависимость
# -1 - отрицательная зависимость
# 0 - отсутствие линейной зависимости

# -0.111054 - зарплата незначительно уменьшается с возрастом

          Salary       Age
Salary  1.000000 -0.111054
Age    -0.111054  1.000000

In [75]:
employee.to_csv("data/employees.csv")

In [76]:
employees = pd.read_csv("data/employees.csv")  # Проблема с индексами
employees

  Unnamed: 0  Salary  Age    Отдел
0       Mary      65   26  Продажи
1       Paul      45   46  Продажи
2      Sasha      40   20  Продажи

In [77]:
employees = pd.read_csv("data/employees.csv", index_col=0)  # Первая колонка - индексы
employees

       Salary  Age    Отдел
Mary       65   26  Продажи
Paul       45   46  Продажи
Sasha      40   20  Продажи

In [78]:
employees = pd.DataFrame(
    {
        "Имя": ["Маша", "Паша", "Женя"],
        "Зарплата": [60, 45, 50],
        "Возраст": [26, 45, 30]
    }
)

In [79]:
employees.to_csv("data/employees2.csv", index=False)

In [80]:
employees2 = pd.read_csv("data/employees2.csv")

In [81]:
employees2

    Имя  Зарплата  Возраст
0  Маша        60       26
1  Паша        45       45
2  Женя        50       30

**Python Data Analysis** == *Pandas*.

**Panel Data** - термин, созвучный *Pandas*.

Книга для обучения на английском: https://www.lkhibra.ma/books/Python-for-Data-Analysis.pdf