In [1]:
import pandas as pd

## Задача 1

Дан файл "titanic.csv" в формате .csv.

При проверке файл будет находиться в одной директории с Вашим решением, поэтому его можно открыть командой pd.read_csv("titanic.csv").

Каждая строка этого набора данных - это отдельный человек, которому присвоен набор свойств - имя, номер каюты, возраст и т.д.

В данной задаче необходимо определить количество людей в наборе данных, возраст которых находится в диапазоне строго между M и N, где M и N - целые числа от 0 до 100, которые подаются на вход Вашего скрипта в виде аргументов. Решение нужно оформить в виде функции, принимающей два аргумента (например, ageSearch(M, N)). Функция должна возвращать одно целое число - количество пассажиров Титаника, удовлетворяющих условию.

In [2]:
titanic = pd.read_csv("data/titanic.csv")

In [3]:
titanic.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [4]:
def ageSearch(M, N):
    titanic_forage = titanic[(titanic["Age"] > M) & (titanic["Age"] < N)]
    return len(titanic_forage)


ageSearch(1, 10)

48

## Задача 2

Создайте таблицу, включающую только страны с плотностью населения (Density (P/Km2)) выше 100 человек на квадратный километр.

Сохраните результат в файл high_density_countries.csv.

К файлу-источнику можно обратиться по имени world-data-2023.csv.

Источник данных - https://www.kaggle.com/datasets/nelgiriyewithana/countries-of-the-world-2023

In [5]:
countries = pd.read_csv("data/world-data-2023.csv")

In [6]:
countries.head()

,Country,Density\n(P/Km2),Abbreviation,Agricultural Land( %),Land Area(Km2),Armed Forces size,Birth Rate,Calling Code,Capital/Major City,Co2-Emissions,...,Out of pocket health expenditure,Physicians per thousand,Population,Population: Labor force participation (%),Tax revenue (%),Total tax rate,Unemployment rate,Urban_population,Latitude,Longitude
0,Afghanistan,60,AF,58.10%,"652,230","323,000",32.49,93.0,Kabul,"8,672",...,78.40%,0.28,"38,041,754",48.90%,9.30%,71.40%,11.12%,"9,797,273",33.939110,67.709953
1,Albania,105,AL,43.10%,"28,748","9,000",11.78,355.0,Tirana,"4,536",...,56.90%,1.20,"2,854,191",55.70%,18.60%,36.60%,12.33%,"1,747,593",41.153332,20.168331
2,Algeria,18,DZ,17.40%,"2,381,741","317,000",24.28,213.0,Algiers,"150,006",...,28.10%,1.72,"43,053,054",41.20%,37.20%,66.10%,11.70%,"31,510,100",28.033886,1.659626
3,Andorra,164,AD,40.00%,468,NaN,7.20,376.0,Andorra la Vella,469,...,36.40%,3.33,"77,142",NaN,NaN,NaN,NaN,"67,873",42.506285,1.521801
4,Angola,26,AO,47.50%,"1,246,700","117,000",40.73,244.0,Luanda,"34,693",...,33.40%,0.21,"31,825,295",77.50%,9.20%,49.10%,6.89%,"21,061,025",-11.202692,17.873887

In [7]:
countries["Density\n(P/Km2)"] = pd.to_numeric(countries["Density\n(P/Km2)"].str.replace(",", ""))

In [8]:
high_density_countries = countries[countries["Density\n(P/Km2)"] > 100]

In [9]:
high_density_countries.head()

,Country,Density\n(P/Km2),Abbreviation,Agricultural Land( %),Land Area(Km2),Armed Forces size,Birth Rate,Calling Code,Capital/Major City,Co2-Emissions,...,Out of pocket health expenditure,Physicians per thousand,Population,Population: Labor force participation (%),Tax revenue (%),Total tax rate,Unemployment rate,Urban_population,Latitude,Longitude
1,Albania,105,AL,43.10%,"28,748","9,000",11.78,355.0,Tirana,"4,536",...,56.90%,1.20,"2,854,191",55.70%,18.60%,36.60%,12.33%,"1,747,593",41.153332,20.168331
3,Andorra,164,AD,40.00%,468,NaN,7.20,376.0,Andorra la Vella,469,...,36.40%,3.33,"77,142",NaN,NaN,NaN,NaN,"67,873",42.506285,1.521801
5,Antigua and Barbuda,223,AG,20.50%,443,0,15.33,1.0,"St. John's, Saint John",557,...,24.30%,2.76,"97,118",NaN,16.50%,43.00%,NaN,"23,800",17.060816,-61.796428
7,Armenia,104,AM,58.90%,"29,743","49,000",13.99,374.0,Yerevan,"5,156",...,81.60%,4.40,"2,957,731",55.60%,20.90%,22.60%,16.99%,"1,869,848",40.069099,45.038189
9,Austria,109,AT,32.40%,"83,871","21,000",9.70,43.0,Vienna,"61,448",...,17.90%,5.17,"8,877,067",60.70%,25.40%,51.40%,4.67%,"5,194,416",47.516231,14.550072

In [10]:
high_density_countries.to_csv("data/high_density_countries.csv", index=False)

## Задача 3

Найдите страны с продолжительностью жизни выше среднего по миру. Отсортируйте результат по убыванию продолжительности жизни и выведите колонки с названием страны и продолжительностью жизни "Country" и "Life Expectancy" соответственно.

Сохраните результат в CSV-файл с именем high_life_expectancy_countries.csv.

К файлу-источнику можно обратиться по имени world-data-2023.csv.

Источник данных - https://www.kaggle.com/datasets/nelgiriyewithana/countries-of-the-world-2023

In [11]:
countries = pd.read_csv("data/world-data-2023.csv")

In [12]:
countries.info()

<class 'pandas.DataFrame'>
RangeIndex: 195 entries, 0 to 194
Data columns (total 35 columns):
 #   Column                                     Non-Null Count  Dtype
---  ------                                     --------------  -----
 0   Country                                    195 non-null    str
 1   Density
(P/Km2)                            195 non-null    str
 2   Abbreviation                               188 non-null    str
 3   Agricultural Land( %)                      188 non-null    str
 4   Land Area(Km2)                             194 non-null    str
 5   Armed Forces size                          171 non-null    str
 6   Birth Rate                                 189 non-null    float64
 7   Calling Code                               194 non-null    float64
 8   Capital/Major City                         192 non-null    str
 9   Co2-Emissions                              188 non-null    str
 10  CPI                                        178 non-null    str
 11  CPI Change (%)                             179 non-null    str
 12  Currency-Code                              180 non-null    str
 13  Fertility Rate                             188 non-null    float64
 14  Forested Area (%)                          188 non-null    str
 15  Gasoline Price                             175 non-null    str
 16  GDP                                        193 non-null    str
 17  Gross primary education enrollment (%)     188 non-null    str
 18  Gross tertiary education enrollment (%)    183 non-null    str
 19  Infant mortality                           189 non-null    float64
 20  Largest city                               189 non-null    str
 21  Life expectancy                            187 non-null    float64
 22  Maternal mortality ratio                   181 non-null    float64
 23  Minimum wage                               150 non-null    str
 24  Official language                          190 non-null    str
 25  Out of pocket health expenditure           188 non-null    str
 26  Physicians per thousand                    188 non-null    float64
 27  Population                                 194 non-null    str
 28  Population: Labor force participation (%)  176 non-null    str
 29  Tax revenue (%)                            169 non-null    str
 30  Total tax rate                             183 non-null    str
 31  Unemployment rate                          176 non-null    str
 32  Urban_population                           190 non-null    str
 33  Latitude                                   194 non-null    float64
 34  Longitude                                  194 non-null    float64
dtypes: float64(9), str(26)
memory usage: 84.6 KB

In [13]:
age_mean = countries["Life expectancy"].mean()

In [14]:
high_life_expectancy_countries = countries[countries["Life expectancy"] > age_mean]

In [15]:
high_life_expectancy_countries = high_life_expectancy_countries[["Country", "Life expectancy"]].sort_values("Life expectancy", ascending=False)

In [16]:
high_life_expectancy_countries

                              Country  Life expectancy
149                        San Marino             85.4
85                              Japan             84.2
169                       Switzerland             83.6
164                             Spain             83.3
156                         Singapore             83.1
..                                ...              ...
97                              Libya             72.7
143                            Russia             72.7
67                            Grenada             72.4
147  Saint Vincent and the Grenadines             72.4
13                         Bangladesh             72.3

[105 rows x 2 columns]

In [17]:
high_life_expectancy_countries.to_csv("data/high_life_expectancy_countries.csv", index=False)

## Задача 4

Создайте таблицу, включающую страны, где процент сельскохозяйственной земли (Agricultural Land( %)) составляет более 50%.

Сохраните результат в файл high_agriculture_land_countries.csv.

К файлу-источнику можно обратиться по имени world-data-2023.csv.

Источник данных - https://www.kaggle.com/datasets/nelgiriyewithana/countries-of-the-world-2023

In [18]:
countries = pd.read_csv("data/world-data-2023.csv")

In [19]:
countries["Agricultural Land( %)"]

0      58.10%
1      43.10%
2      17.40%
3      40.00%
4      47.50%
        ...
190    24.50%
191    39.30%
192    44.60%
193    32.10%
194    41.90%
Name: Agricultural Land( %), Length: 195, dtype: str

In [20]:
countries["Agricultural Land( %)"] = countries["Agricultural Land( %)"].str.replace("%", "")

In [21]:
countries["Agricultural Land( %)"] = pd.to_numeric(countries["Agricultural Land( %)"], errors="coerce")

In [22]:
high_agriculture_land_countries = countries[countries["Agricultural Land( %)"] > 50]

In [23]:
high_agriculture_land_countries.to_csv("data/high_agriculture_land_countries.csv", index=False)

## Задача 5

Рассчитайте средний ВВП по всем странам и добавьте его как новый столбец в таблицу.

Очистите данные в столбце GDP, удалив спецсимволы, такие как $ и запятые, и преобразуйте его значения в числовой формат (float).

Рассчитайте средний ВВП по всем странам и добавьте его как новый столбец "Average GDP", который будет содержать одно и то же значение среднего ВВП для каждой строки.

Сохраните таблицу с этим столбцом в файл countries_with_avg_gdp.csv.

К файлу-источнику можно обратиться по имени world-data-2023.csv.

Источник данных - https://www.kaggle.com/datasets/nelgiriyewithana/countries-of-the-world-2023

In [24]:
countries = pd.read_csv("data/world-data-2023.csv")

In [25]:
countries["GDP"]

0       $19,101,353,833
1       $15,278,077,447
2      $169,988,236,398
3        $3,154,057,987
4       $94,635,415,870
             ...
190    $482,359,318,768
191    $261,921,244,843
192     $26,914,402,224
193     $23,064,722,446
194     $21,440,758,800
Name: GDP, Length: 195, dtype: str

In [26]:
countries["GDP"] = countries["GDP"].str.replace("$", "")
countries["GDP"] = countries["GDP"].str.replace(",", "")

In [27]:
countries["GDP"] = pd.to_numeric(countries["GDP"], errors="coerce")

In [28]:
average_gdp = countries["GDP"].mean()

In [29]:
countries["Average GDP"] = average_gdp

In [30]:
countries.to_csv("data/countries_with_avg_gdp.csv", index=False)

## Задача 6

Найдите страны с самой высокой и самой низкой ожидаемой продолжительностью жизни (Life expectancy) и создайте таблицу с этими двумя записями.

Сохраните результат в файл extreme_life_expectancy.csv.

К файлу-источнику можно обратиться по имени world-data-2023.csv.

Источник данных - https://www.kaggle.com/datasets/nelgiriyewithana/countries-of-the-world-2023

In [31]:
countries = pd.read_csv("data/world-data-2023.csv")

In [32]:
max_age = countries["Life expectancy"].max()
min_age = countries["Life expectancy"].min()
extreme_life_expectancy = countries[(countries["Life expectancy"] == max_age) | (countries["Life expectancy"] == min_age)]  # Может вернуть дубликаты

In [33]:
min_idx = countries["Life expectancy"].idxmin()
max_idx = countries["Life expectancy"].idxmax()

In [34]:
extreme_life_expectancy = countries.loc[[min_idx, max_idx]]

In [35]:
extreme_life_expectancy.to_csv("data/extreme_life_expectancy.csv", index=False)

## Задача 7

Отфильтруйте страны, где процент лесных площадей (Forested Area (%)) составляет более 30%.

Сохраните результат в файл high_forested_area_countries.csv.

К файлу-источнику можно обратиться по имени world-data-2023.csv.

Источник данных - https://www.kaggle.com/datasets/nelgiriyewithana/countries-of-the-world-2023

In [36]:
countries = pd.read_csv("data/world-data-2023.csv")

In [37]:
countries["Forested Area (%)"]

0       2.10%
1      28.10%
2       0.80%
3      34.00%
4      46.30%
        ...
190    52.70%
191    48.10%
192     1.00%
193    65.20%
194    35.50%
Name: Forested Area (%), Length: 195, dtype: str

In [38]:
countries["Forested Area (%)"] = countries["Forested Area (%)"].str.replace("%", "")

In [39]:
countries["Forested Area (%)"] = pd.to_numeric(countries["Forested Area (%)"], errors="coerce")

In [40]:
high_forested_area_countries = countries[countries["Forested Area (%)"] > 30]

In [41]:
high_forested_area_countries.to_csv("data/high_forested_area_countries.csv", index=False)

## Задача 8

Создайте таблицу, включающую только страны с уровнем младенческой смертности (Infant mortality) выше 20 на 1000 рождений.

Сохраните результат в файл high_infant_mortality_countries.csv.

К файлу-источнику можно обратиться по имени world-data-2023.csv.

Источник данных - https://www.kaggle.com/datasets/nelgiriyewithana/countries-of-the-world-2023

In [42]:
countries = pd.read_csv("data/world-data-2023.csv")

In [43]:
countries["Infant mortality"]

0      47.9
1       7.8
2      20.1
3       2.7
4      51.6
       ...
190    21.4
191    16.5
192    42.9
193    40.4
194    33.9
Name: Infant mortality, Length: 195, dtype: float64

In [44]:
high_infant_mortality_countries = countries[countries["Infant mortality"] > 20]

In [45]:
high_infant_mortality_countries

,Country,Density\n(P/Km2),Abbreviation,Agricultural Land( %),Land Area(Km2),Armed Forces size,Birth Rate,Calling Code,Capital/Major City,Co2-Emissions,...,Out of pocket health expenditure,Physicians per thousand,Population,Population: Labor force participation (%),Tax revenue (%),Total tax rate,Unemployment rate,Urban_population,Latitude,Longitude
0,Afghanistan,60,AF,58.10%,"652,230","323,000",32.49,93.0,Kabul,"8,672",...,78.40%,0.28,"38,041,754",48.90%,9.30%,71.40%,11.12%,"9,797,273",33.939110,67.709953
2,Algeria,18,DZ,17.40%,"2,381,741","317,000",24.28,213.0,Algiers,"150,006",...,28.10%,1.72,"43,053,054",41.20%,37.20%,66.10%,11.70%,"31,510,100",28.033886,1.659626
4,Angola,26,AO,47.50%,"1,246,700","117,000",40.73,244.0,Luanda,"34,693",...,33.40%,0.21,"31,825,295",77.50%,9.20%,49.10%,6.89%,"21,061,025",-11.202692,17.873887
13,Bangladesh,"1,265",BD,70.60%,"148,460","221,000",18.18,880.0,Dhaka,"84,246",...,71.80%,0.58,"167,310,838",59.00%,8.80%,33.40%,4.19%,"60,987,417",23.684994,90.356331
18,Benin,108,BJ,33.30%,"112,622","12,000",36.22,229.0,Porto-Novo,"6,476",...,40.50%,0.08,"11,801,151",70.90%,10.80%,48.90%,2.23%,"5,648,149",9.307690,2.315834
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
189,Vanuatu,25,VU,15.30%,"12,189",NaN,29.60,678.0,Port Vila,147,...,8.90%,0.17,"299,882",69.90%,17.80%,8.50%,4.39%,"76,152",-15.376706,166.959158
190,Venezuela,32,VE,24.50%,"912,050","343,000",17.88,58.0,Caracas,"164,175",...,45.80%,1.92,"28,515,829",59.70%,NaN,73.30%,8.80%,"25,162,368",6.423750,-66.589730
192,Yemen,56,YE,44.60%,"527,968","40,000",30.45,967.0,Sanaa,"10,609",...,81.00%,0.31,"29,161,922",38.00%,NaN,26.60%,12.91%,"10,869,523",15.552727,48.516388
193,Zambia,25,ZM,32.10%,"752,618","16,000",36.19,260.0,Lusaka,"5,141",...,27.50%,1.19,"17,861,030",74.60%,16.20%,15.60%,11.43%,"7,871,713",-13.133897,27.849332
194,Zimbabwe,38,ZW,41.90%,"390,757","51,000",30.68,263.0,Harare,"10,983",...,25.80%,0.21,"14,645,468",83.10%,20.70%,31.60%,4.95%,"4,717,305",-19.015438,29.154857

In [46]:
high_infant_mortality_countries.to_csv("data/high_infant_mortality_countries.csv", index=False)

## Задача 9

Отфильтруйте страны с уровнем безработицы (Unemployment rate) менее 5%.

Сохраните результат в файл low_unemployment_countries.csv.

К файлу-источнику можно обратиться по имени world-data-2023.csv.

Источник данных - https://www.kaggle.com/datasets/nelgiriyewithana/countries-of-the-world-2023

In [47]:
countries = pd.read_csv("data/world-data-2023.csv")

In [48]:
countries["Unemployment rate"]

0      11.12%
1      12.33%
2      11.70%
3         NaN
4       6.89%
        ...
190     8.80%
191     2.01%
192    12.91%
193    11.43%
194     4.95%
Name: Unemployment rate, Length: 195, dtype: str

In [49]:
countries["Unemployment rate"] = countries["Unemployment rate"].str.replace("%", "")

In [50]:
countries["Unemployment rate"] = pd.to_numeric(countries["Unemployment rate"], errors="coerce")

In [51]:
low_unemployment_countries = countries[countries["Unemployment rate"] < 5]

In [52]:
low_unemployment_countries.to_csv("data/low_unemployment_countries.csv", index=False)

## Задача 10

Добавьте в таблицу столбец с отношением городского населения к общему населению для каждой страны.

Создайте новый столбец "Urban Population Ratio", который будет содержать отношение городского населения (Urban_population) к общему населению (Population) для каждой страны.

Убедитесь, что значения в новом столбце имеют числовой формат (float).

Сохраните таблицу с этим новым столбцом в файл urban_population_ratio.csv.

К файлу-источнику можно обратиться по имени world-data-2023.csv.

Источник данных - https://www.kaggle.com/datasets/nelgiriyewithana/countries-of-the-world-2023

In [53]:
countries = pd.read_csv("data/world-data-2023.csv")

In [54]:
countries["Urban_population"]

0       9,797,273
1       1,747,593
2      31,510,100
3          67,873
4      21,061,025
          ...
190    25,162,368
191    35,332,140
192    10,869,523
193     7,871,713
194     4,717,305
Name: Urban_population, Length: 195, dtype: str

In [55]:
countries["Population"]

0      38,041,754
1       2,854,191
2      43,053,054
3          77,142
4      31,825,295
          ...
190    28,515,829
191    96,462,106
192    29,161,922
193    17,861,030
194    14,645,468
Name: Population, Length: 195, dtype: str

In [56]:
countries["Urban_population"] = countries["Urban_population"].str.replace(",", "")
countries["Population"] = countries["Population"].str.replace(",", "")

In [57]:
countries["Urban_population"] = pd.to_numeric(countries["Urban_population"], errors="coerce")
countries["Population"] = pd.to_numeric(countries["Population"], errors="coerce")

In [58]:
countries["Urban Population Ratio"] = countries["Urban_population"] / countries["Population"]

In [59]:
countries

,Country,Density\n(P/Km2),Abbreviation,Agricultural Land( %),Land Area(Km2),Armed Forces size,Birth Rate,Calling Code,Capital/Major City,Co2-Emissions,...,Physicians per thousand,Population,Population: Labor force participation (%),Tax revenue (%),Total tax rate,Unemployment rate,Urban_population,Latitude,Longitude,Urban Population Ratio
0,Afghanistan,60,AF,58.10%,"652,230","323,000",32.49,93.0,Kabul,"8,672",...,0.28,38041754.0,48.90%,9.30%,71.40%,11.12%,9797273.0,33.939110,67.709953,0.257540
1,Albania,105,AL,43.10%,"28,748","9,000",11.78,355.0,Tirana,"4,536",...,1.20,2854191.0,55.70%,18.60%,36.60%,12.33%,1747593.0,41.153332,20.168331,0.612290
2,Algeria,18,DZ,17.40%,"2,381,741","317,000",24.28,213.0,Algiers,"150,006",...,1.72,43053054.0,41.20%,37.20%,66.10%,11.70%,31510100.0,28.033886,1.659626,0.731890
3,Andorra,164,AD,40.00%,468,NaN,7.20,376.0,Andorra la Vella,469,...,3.33,77142.0,NaN,NaN,NaN,NaN,67873.0,42.506285,1.521801,0.879845
4,Angola,26,AO,47.50%,"1,246,700","117,000",40.73,244.0,Luanda,"34,693",...,0.21,31825295.0,77.50%,9.20%,49.10%,6.89%,21061025.0,-11.202692,17.873887,0.661770
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
190,Venezuela,32,VE,24.50%,"912,050","343,000",17.88,58.0,Caracas,"164,175",...,1.92,28515829.0,59.70%,NaN,73.30%,8.80%,25162368.0,6.423750,-66.589730,0.882400
191,Vietnam,314,VN,39.30%,"331,210","522,000",16.75,84.0,Hanoi,"192,668",...,0.82,96462106.0,77.40%,19.10%,37.60%,2.01%,35332140.0,14.058324,108.277199,0.366280
192,Yemen,56,YE,44.60%,"527,968","40,000",30.45,967.0,Sanaa,"10,609",...,0.31,29161922.0,38.00%,NaN,26.60%,12.91%,10869523.0,15.552727,48.516388,0.372730
193,Zambia,25,ZM,32.10%,"752,618","16,000",36.19,260.0,Lusaka,"5,141",...,1.19,17861030.0,74.60%,16.20%,15.60%,11.43%,7871713.0,-13.133897,27.849332,0.440720
194,Zimbabwe,38,ZW,41.90%,"390,757","51,000",30.68,263.0,Harare,"10,983",...,0.21,14645468.0,83.10%,20.70%,31.60%,4.95%,4717305.0,-19.015438,29.154857,0.322100

In [60]:
countries.to_csv("data/urban_population_ratio.csv", index=False)