# **Pandas Tutorial**

video from: **Complete Python Pandas Data Science Tutorial! (2025 Updated Edition)** - https://www.youtube.com/watch?v=2uvysYbKdjM

Dataset: https://www.kaggle.com/datasets/heesoo37/120-years-of-olympic-history-athletes-and-results

Article about pyarrow in pandas: https://datapythonista.me/blog/pandas-20-and-the-arrow-revolution-part-i

### Часть 1. **Базовые методы и атрибуты**

In [1]:
import pandas as pd

In [2]:
# Названия колонок часто есть по умолчанию во входных файлах
# Названия строк можно тоже не давать. По умолчанию все: 0, 1, 2, ...
df = pd.DataFrame([[1, 2, 3], [4, 5, 6], [7, 8, 9]], columns=["A", "B", "C"], index=["x", "y", "z"])

df.head()  # Вывод первых 5 записей

   A  B  C
x  1  2  3
y  4  5  6
z  7  8  9

In [3]:
df.head(2)  # Вывод первых 2 записей

   A  B  C
x  1  2  3
y  4  5  6

In [4]:
df.tail(2)  # Вывод последних 2 записей

   A  B  C
y  4  5  6
z  7  8  9

In [5]:
df  # Вывод всего фрейма

   A  B  C
x  1  2  3
y  4  5  6
z  7  8  9

In [6]:
df.columns  # Названия колонок; можно с .to_list()

Index(['A', 'B', 'C'], dtype='str')

In [7]:
df.index  # Названия строк

Index(['x', 'y', 'z'], dtype='str')

In [8]:
df.index.to_list()  # Названия строк в виде списка

['x', 'y', 'z']

In [9]:
df.info()

<class 'pandas.DataFrame'>
Index: 3 entries, x to z
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   A       3 non-null      int64
 1   B       3 non-null      int64
 2   C       3 non-null      int64
dtypes: int64(3)
memory usage: 99.0 bytes

In [10]:
df.describe()  # Информация для каждого столбца
# Количество элементов
# Среднее
# Стандартное отклонение
# Минимальное значение
# и т.д.

         A    B    C
count  3.0  3.0  3.0
mean   4.0  5.0  6.0
std    3.0  3.0  3.0
min    1.0  2.0  3.0
25%    2.5  3.5  4.5
50%    4.0  5.0  6.0
75%    5.5  6.5  7.5
max    7.0  8.0  9.0

In [11]:
df.nunique()  # Количество уникальных элементов в столбцах

A    3
B    3
C    3
dtype: int64

In [12]:
df["A"].unique()  # Уникальные значения для конкретного столбца

array([1, 4, 7])

In [13]:
df.shape  # Форма фрейма: (строк, столбцов)

(3, 3)

In [14]:
df.size  # Количество элементов во фрейме

9

### Часть 2. **Работа с датасетом**

In [15]:
coffee = pd.read_csv("https://raw.githubusercontent.com/KeithGalli/complete-pandas-tutorial/refs/heads/master/warmup-data/coffee.csv")
# coffee = pd.read_csv("data/coffee.csv") - если файл есть в проекте

In [16]:
coffee.head()

         Day Coffee Type  Units Sold
0     Monday    Espresso          25
1     Monday       Latte          15
2    Tuesday    Espresso          30
3    Tuesday       Latte          20
4  Wednesday    Espresso          35

In [17]:
# results = pd.read_feather("data/results.feather")
# results = pd.read_parquet("data/results.parquet")

# results = pd.read_excel("data/olympics-data.xlsx")
# results = pd.read_excel("data/olympics-data.xlsx", sheet_name="results")  # С выбором листа из нескольких таблиц в файле

results = pd.read_csv("data/results.csv")
bios = pd.read_csv("data/bios.csv")
noc_regions = pd.read_csv("data/noc_regions.csv")

In [18]:
results.head()

,year,type,discipline,event,as,athlete_id,noc,team,place,tied,medal
0,1912.0,Summer,Tennis,"Singles, Men (Olympic)",Jean-François Blanchy,1,FRA,NaN,17.0,True,NaN
1,1912.0,Summer,Tennis,"Doubles, Men (Olympic)",Jean-François Blanchy,1,FRA,Jean Montariol,NaN,False,NaN
2,1920.0,Summer,Tennis,"Singles, Men (Olympic)",Jean-François Blanchy,1,FRA,NaN,32.0,True,NaN
3,1920.0,Summer,Tennis,"Doubles, Mixed (Olympic)",Jean-François Blanchy,1,FRA,Jeanne Vaussard,8.0,True,NaN
4,1920.0,Summer,Tennis,"Doubles, Men (Olympic)",Jean-François Blanchy,1,FRA,Jacques Brugnon,4.0,False,NaN

In [19]:
bios.head()

,athlete_id,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date
0,1,Jean-François Blanchy,1886-12-12,Bordeaux,Gironde,FRA,France,NaN,NaN,1960-10-02
1,2,Arnaud Boetsch,1969-04-01,Meulan,Yvelines,FRA,France,183.0,76.0,NaN
2,3,Jean Borotra,1898-08-13,Biarritz,Pyrénées-Atlantiques,FRA,France,183.0,76.0,1994-07-17
3,4,Jacques Brugnon,1895-05-11,Paris VIIIe,Paris,FRA,France,168.0,64.0,1978-03-20
4,5,Albert Canet,1878-04-17,Wandsworth,England,GBR,France,NaN,NaN,1930-07-25

In [20]:
noc_regions.head()

   NOC       region                 notes
0  AFG  Afghanistan                   NaN
1  AHO      Curacao  Netherlands Antilles
2  ALB      Albania                   NaN
3  ALG      Algeria                   NaN
4  AND      Andorra                   NaN

In [21]:
results

,year,type,discipline,event,as,athlete_id,noc,team,place,tied,medal
0,1912.0,Summer,Tennis,"Singles, Men (Olympic)",Jean-François Blanchy,1,FRA,NaN,17.0,True,NaN
1,1912.0,Summer,Tennis,"Doubles, Men (Olympic)",Jean-François Blanchy,1,FRA,Jean Montariol,NaN,False,NaN
2,1920.0,Summer,Tennis,"Singles, Men (Olympic)",Jean-François Blanchy,1,FRA,NaN,32.0,True,NaN
3,1920.0,Summer,Tennis,"Doubles, Mixed (Olympic)",Jean-François Blanchy,1,FRA,Jeanne Vaussard,8.0,True,NaN
4,1920.0,Summer,Tennis,"Doubles, Men (Olympic)",Jean-François Blanchy,1,FRA,Jacques Brugnon,4.0,False,NaN
...,...,...,...,...,...,...,...,...,...,...,...
308403,2022.0,Winter,Luge,"Singles, Men (Olympic)",Marián Skupek,148983,SVK,NaN,26.0,False,NaN
308404,2022.0,Winter,Alpine Skiing (Skiing),"Slalom, Women (Olympic)",Elsa Fermbäck,148984,SWE,NaN,28.0,False,NaN
308405,2022.0,Winter,Alpine Skiing (Skiing),"Team, Mixed (Olympic)",Hilma Lövblom,148985,SWE,Sweden,13.0,False,NaN
308406,2022.0,Winter,Alpine Skiing (Skiing),"Giant Slalom, Women (Olympic)",Hilma Lövblom,148985,SWE,NaN,NaN,False,NaN
308407,2022.0,Winter,NaN,"Slalom, Women (Olympic)",Charlotta Säfvenberg,148986,NaN,NaN,24.0,False,NaN

In [22]:
display(results)  # == results, если редактор не поддерживает более простой синтаксис

,year,type,discipline,event,as,athlete_id,noc,team,place,tied,medal
0,1912.0,Summer,Tennis,"Singles, Men (Olympic)",Jean-François Blanchy,1,FRA,NaN,17.0,True,NaN
1,1912.0,Summer,Tennis,"Doubles, Men (Olympic)",Jean-François Blanchy,1,FRA,Jean Montariol,NaN,False,NaN
2,1920.0,Summer,Tennis,"Singles, Men (Olympic)",Jean-François Blanchy,1,FRA,NaN,32.0,True,NaN
3,1920.0,Summer,Tennis,"Doubles, Mixed (Olympic)",Jean-François Blanchy,1,FRA,Jeanne Vaussard,8.0,True,NaN
4,1920.0,Summer,Tennis,"Doubles, Men (Olympic)",Jean-François Blanchy,1,FRA,Jacques Brugnon,4.0,False,NaN
...,...,...,...,...,...,...,...,...,...,...,...
308403,2022.0,Winter,Luge,"Singles, Men (Olympic)",Marián Skupek,148983,SVK,NaN,26.0,False,NaN
308404,2022.0,Winter,Alpine Skiing (Skiing),"Slalom, Women (Olympic)",Elsa Fermbäck,148984,SWE,NaN,28.0,False,NaN
308405,2022.0,Winter,Alpine Skiing (Skiing),"Team, Mixed (Olympic)",Hilma Lövblom,148985,SWE,Sweden,13.0,False,NaN
308406,2022.0,Winter,Alpine Skiing (Skiing),"Giant Slalom, Women (Olympic)",Hilma Lövblom,148985,SWE,NaN,NaN,False,NaN
308407,2022.0,Winter,NaN,"Slalom, Women (Olympic)",Charlotta Säfvenberg,148986,NaN,NaN,24.0,False,NaN

In [23]:
results.sample()  # Случайная запись. Можно задать количество записей на вывод

,year,type,discipline,event,as,athlete_id,noc,team,place,tied,medal
125510,NaN,NaN,Weightlifting,"Unlimited, One Hand, Men (Intercalated)",Stefanos Christopoulos,58481,GRE,NaN,11.0,False,NaN

In [24]:
results.sample(4, random_state=15)  # Подобно seed в алгоритмах результат при фиксированном числе будет единственный

,year,type,discipline,event,as,athlete_id,noc,team,place,tied,medal
160715,1952.0,Summer,Athletics,"200 metres, Men (Olympic)",Boonterm Pakpuang,76798,THA,NaN,2.0,False,NaN
56814,1972.0,Summer,Artistic Gymnastics (Gymnastics),"Floor Exercise, Women (Olympic)",Zdena Dorňáková,29120,TCH,NaN,11.0,True,NaN
90068,1972.0,Summer,Shooting,"Running Target, 50 metres, Open (Olympic)",John Kynoch,42350,GBR,NaN,3.0,False,Bronze
93165,1956.0,Summer,Shooting,"Small-Bore Rifle, Prone, 50 metres, Men (Olympic)",César Jayme,43660,PHI,NaN,23.0,False,NaN

### Поподробнее про `random_state=`

In [25]:
import pandas as pd


df = pd.DataFrame({'A': [1, 2, 3, 4, 5], 'B': [6, 7, 8, 9, 10]})

# Без random_state — результат каждый раз разный
print(df.sample(n=2))

# С random_state=42 — результат всегда одинаковый
print(df.sample(n=2, random_state=42))

   A  B
2  3  8
3  4  9
   A   B
1  2   7
4  5  10

In [26]:
coffee.loc[[]]  # Шапка таблицы
coffee.loc[[1]]  # Шапка таблицы + 1 запись
coffee.loc[[1, 4, 8]]  # Шапка таблицы + конкретные записи

# Срезы
coffee.loc[7:]
coffee.loc[:7]
coffee.loc[5:7]

# Можно выбирать конкретные строки и столбцы
coffee.loc[5:7, "Coffee Type"]
coffee.loc[5:7, ["Day", "Coffee Type"]]
coffee.loc[:, ["Day", "Coffee Type"]]  # Все записи, но конкретные столбцы

coffee.iloc[:, [0, 1]]  # В .iloc[] для выборки столбцов пишем индексы, а не имена

          Day Coffee Type
0      Monday    Espresso
1      Monday       Latte
2     Tuesday    Espresso
3     Tuesday       Latte
4   Wednesday    Espresso
5   Wednesday       Latte
6    Thursday    Espresso
7    Thursday       Latte
8      Friday    Espresso
9      Friday       Latte
10   Saturday    Espresso
11   Saturday       Latte
12     Sunday    Espresso
13     Sunday       Latte

In [27]:
coffee.index = coffee["Day"]  # Сами задаём (переопределяем) индексы для фрейма
coffee.head()

coffee.loc["Monday":"Friday", "Coffee Type"]  # Теперь пользуемся именнованными индексами, в противном случае будет ошибка
coffee.iloc[0:2]  # Тут всё как и было, только в таблице числовых индексов больше нет

           Day Coffee Type  Units Sold
Day
Monday  Monday    Espresso          25
Monday  Monday       Latte          15

In [28]:
coffee.head()

                 Day Coffee Type  Units Sold
Day
Monday        Monday    Espresso          25
Monday        Monday       Latte          15
Tuesday      Tuesday    Espresso          30
Tuesday      Tuesday       Latte          20
Wednesday  Wednesday    Espresso          35

In [29]:
coffee.loc["Monday", "Units Sold"] = 1  # Меняем значения. Индексы переопределены, поэтому пишем не цифры
coffee.loc["Tuesday":"Wednesday", "Units Sold"] = 5  # Можно пользоваться срезами

In [30]:
coffee.head()

                 Day Coffee Type  Units Sold
Day
Monday        Monday    Espresso           1
Monday        Monday       Latte           1
Tuesday      Tuesday    Espresso           5
Tuesday      Tuesday       Latte           5
Wednesday  Wednesday    Espresso           5

In [31]:
# Быстро вывести конкретный элемент. Срезы не допускаются. Аналоги .loc[] и .iloc[]
coffee.at["Monday", "Coffee Type"]
coffee.iat[0, 1]

'Espresso'

In [32]:
coffee["Day"]

Day
Monday          Monday
Monday          Monday
Tuesday        Tuesday
Tuesday        Tuesday
Wednesday    Wednesday
Wednesday    Wednesday
Thursday      Thursday
Thursday      Thursday
Friday          Friday
Friday          Friday
Saturday      Saturday
Saturday      Saturday
Sunday          Sunday
Sunday          Sunday
Name: Day, dtype: str

In [33]:
coffee.Day  # Если название столбца - одно слово, можно использовать такой синтаксис

Day
Monday          Monday
Monday          Monday
Tuesday        Tuesday
Tuesday        Tuesday
Wednesday    Wednesday
Wednesday    Wednesday
Thursday      Thursday
Thursday      Thursday
Friday          Friday
Friday          Friday
Saturday      Saturday
Saturday      Saturday
Sunday          Sunday
Sunday          Sunday
Name: Day, dtype: str

In [34]:
coffee.sort_values("Units Sold", ascending=False)  # ascending=False - сортировка по убыванию
coffee.sort_values(["Units Sold", "Coffee Type"], ascending=False)  # Сортировка сначала по количеству, потом по названиям
coffee.sort_values(["Units Sold", "Coffee Type"], ascending=[0, 1])  # Алфавитный порядок сортировки

                 Day Coffee Type  Units Sold
Day
Friday        Friday    Espresso          45
Saturday    Saturday    Espresso          45
Sunday        Sunday    Espresso          45
Thursday    Thursday    Espresso          40
Friday        Friday       Latte          35
Saturday    Saturday       Latte          35
Sunday        Sunday       Latte          35
Thursday    Thursday       Latte          30
Tuesday      Tuesday    Espresso           5
Wednesday  Wednesday    Espresso           5
Tuesday      Tuesday       Latte           5
Wednesday  Wednesday       Latte           5
Monday        Monday    Espresso           1
Monday        Monday       Latte           1

In [35]:
for index, row in coffee.iterrows():
    print(index)
    print("\n")
    print(row)  # Можно выводить конкретный элемент: print(row["Units Sold"])
    print("\n\n\n")

Monday


Day              Monday
Coffee Type    Espresso
Units Sold            1
Name: Monday, dtype: object




Monday


Day            Monday
Coffee Type     Latte
Units Sold          1
Name: Monday, dtype: object




Tuesday


Day             Tuesday
Coffee Type    Espresso
Units Sold            5
Name: Tuesday, dtype: object




Tuesday


Day            Tuesday
Coffee Type      Latte
Units Sold           5
Name: Tuesday, dtype: object




Wednesday


Day            Wednesday
Coffee Type     Espresso
Units Sold             5
Name: Wednesday, dtype: object




Wednesday


Day            Wednesday
Coffee Type        Latte
Units Sold             5
Name: Wednesday, dtype: object




Thursday


Day            Thursday
Coffee Type    Espresso
Units Sold           40
Name: Thursday, dtype: object




Thursday


Day            Thursday
Coffee Type       Latte
Units Sold           30
Name: Thursday, dtype: object




Friday


Day              Friday
Coffee Type    Espresso
Units Sold           45
Name: Friday, dtype: object




Friday


Day            Friday
Coffee Type     Latte
Units Sold         35
Name: Friday, dtype: object




Saturday


Day            Saturday
Coffee Type    Espresso
Units Sold           45
Name: Saturday, dtype: object




Saturday


Day            Saturday
Coffee Type       Latte
Units Sold           35
Name: Saturday, dtype: object




Sunday


Day              Sunday
Coffee Type    Espresso
Units Sold           45
Name: Sunday, dtype: object




Sunday


Day            Sunday
Coffee Type     Latte
Units Sold         35
Name: Sunday, dtype: object

In [36]:
bios.head()

,athlete_id,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date
0,1,Jean-François Blanchy,1886-12-12,Bordeaux,Gironde,FRA,France,NaN,NaN,1960-10-02
1,2,Arnaud Boetsch,1969-04-01,Meulan,Yvelines,FRA,France,183.0,76.0,NaN
2,3,Jean Borotra,1898-08-13,Biarritz,Pyrénées-Atlantiques,FRA,France,183.0,76.0,1994-07-17
3,4,Jacques Brugnon,1895-05-11,Paris VIIIe,Paris,FRA,France,168.0,64.0,1978-03-20
4,5,Albert Canet,1878-04-17,Wandsworth,England,GBR,France,NaN,NaN,1930-07-25

In [37]:
bios.info()

<class 'pandas.DataFrame'>
RangeIndex: 145500 entries, 0 to 145499
Data columns (total 10 columns):
 #   Column        Non-Null Count   Dtype
---  ------        --------------   -----
 0   athlete_id    145500 non-null  int64
 1   name          145500 non-null  str
 2   born_date     143693 non-null  str
 3   born_city     110908 non-null  str
 4   born_region   110908 non-null  str
 5   born_country  110908 non-null  str
 6   NOC           145499 non-null  str
 7   height_cm     106651 non-null  float64
 8   weight_kg     102070 non-null  float64
 9   died_date     33940 non-null   str
dtypes: float64(2), int64(1), str(7)
memory usage: 18.5 MB

In [38]:
bios = bios.sort_values("height_cm")  # Сортировка
bios.loc[bios["height_cm"] < 150]  # Фильтрация
bios.loc[bios["height_cm"] < 150, ["name", "height_cm"]]  # Сокращённый фрейм
bios.loc[bios["height_cm"] < 150][["name", "height_cm"]]  # Другой метод получения сокращённого фрейма
# bios.sort_index()  # Сортировка по индексам (возвращает к состоянию до сортировки)

                         name  height_cm
4515            Lyton Mphande      127.0
28619         Rosario Briones      127.0
4516            Helman Palije      128.0
4664         Salvador Miranda      130.0
4517           Boston Simbeye      130.0
...                       ...        ...
99398     Yevheniya Filanenko      149.0
128788             Mary Tabal      149.0
66586          Kriscia García      149.0
106054       Alexandra Eremia      149.0
119716  Soniya Chanu Ngangbam      149.0

[372 rows x 2 columns]

In [39]:
# Двойное условие
bios.loc[(bios["height_cm"] < 150) & (bios["born_country"] == "USA")]
bios.loc[(bios["height_cm"] < 150) & (bios["born_country"] == "USA")][:3]  # Применение среза

,athlete_id,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date
114670,115987,Julianne Kirchner,1991-12-19,Florence,Alabama,USA,Marshall Islands,138.0,54.0,NaN
29088,29302,Kim Zmeskal,1976-02-06,Houston,Texas,USA,United States,139.0,36.0,NaN
56566,56969,Joe DePietro,1914-06-10,Paterson,New Jersey,USA,United States,140.0,56.0,1999-03-19

In [40]:
bios["born_country"]

4515      NaN
28619     MEX
4516      NaN
4664      NaN
4517      NaN
         ...
145490    NaN
145491    NaN
145492    CUB
145493    RUS
145499    AUS
Name: born_country, Length: 145500, dtype: str

In [41]:
bios.loc[bios["born_country"] == "RUS"].count()  # .count() - количество записей в каждом столбце

athlete_id      4276
name            4276
born_date       4276
born_city       4276
born_region     4276
born_country    4276
NOC             4276
height_cm       3599
weight_kg       3488
died_date        852
dtype: int64

In [42]:
bios[bios["name"].str.contains("Yana")]  # Поиск совпадений в столбце имён с учётом регистра
bios[bios["name"].str.contains("yana", case=False)]  # Поиск совпадений в столбце имён без учёта регистра
bios[bios["name"].str.contains("Yana|Nata")]  # Используем синтаксис регулярных выражений
bios.loc[bios["name"].str.contains("Yana|Nata")]  # Можно и с .loc[]
# bios[bios["name"].str.contains("Yana|Nata", regex=False)]  # Поиск с отключенными регулярками

,athlete_id,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date
28222,28434,Natalie Davies,1966-12-01,Farnborough,England,GBR,Great Britain,150.0,47.0,NaN
107060,108180,Nataliya Mikryukova,1983-09-20,NaN,NaN,NaN,Uzbekistan,152.0,49.0,NaN
94146,94907,Natasha Barker,1970-11-30,Sydney,New South Wales,AUS,Australia,153.0,58.0,NaN
100399,101249,Nataliya Ponomaryova,1982-08-13,Yekaterinburg,Sverdlovsk,RUS,Uzbekistan,153.0,NaN,NaN
90507,91230,Natallia Naranovich,1981-08-01,Minsk,Minsk,BLR,Belarus,153.0,42.0,NaN
...,...,...,...,...,...,...,...,...,...,...
144666,148362,Natasha McKay,1995-01-14,Dundee,Scotland,GBR,Great Britain,NaN,NaN,NaN
144875,148580,Yana Khan,2000-09-06,Astana,Astana,KAZ,Kazakhstan,NaN,NaN,NaN
145086,148798,Nataliya Sherina,1999-05-24,Petropavlovsk-Kamchatsky,Kamchatka Kray,RUS,ROC,NaN,NaN,NaN
145159,148876,Natalia Ushkina,1996-09-07,Potma,Respublika Mordoviya,RUS,Romania,NaN,NaN,NaN
145235,148954,Natalie Maag,1997-11-29,Wetzikon,Zürich,SUI,Switzerland,NaN,NaN,NaN

Представим, что в `bios` есть колонки `name`, `email`, `phone`, `bio`.

### 1. Якоря `^` и `$` — привязка к началу/концу строки
```python
# Имена, которые НАЧИНАЮТСЯ с "Dr." (точка экранируется, т.к. в regex . = любой символ)
bios[bios["name"].str.contains(r"^Dr\.", na=False)]

# Биографии, которые ЗАКАНЧИВАЮТСЯ на "PhD"
bios[bios["bio"].str.contains(r"PhD$", na=False)]
```
`^` — начало строки, `$` — конец. Без них `Dr.` нашлось бы и внутри предложения.

### 2. Классы символов и квантификаторы
```python
# Код страны в телефоне: + и 1–3 цифры
bios[bios["phone"].str.contains(r"^\+\d{1,3}\s", na=False)]

# Возраст от 18 до 99 в биографии (две цифры подряд)
bios[bios["bio"].str.contains(r"\b\d{2}\b", na=False)]
```
`\d` — цифра, `{1,3}` — от 1 до 3 повторений, `\b` — граница слова (чтобы "123" не считалось возрастом).

### 3. Валидация email
```python
email_pattern = r"^[\w.+-]+@[\w-]+\.[\w.]+$"
bios[bios["email"].str.contains(email_pattern, na=False)]
```
Разбор: `[\w.+-]+` — один или более символов из букв/цифр/`_`/`.`/`+`/`-`, потом `@`, потом домен, потом точка и TLD.

### 4. Альтернатива с группами — «или» внутри слова
```python
# Имена, содержащие "Ann" или "Anna" (но не "Annabelle")
bios[bios["name"].str.contains(r"\bAnn(a)?\b", na=False)]
```
`(a)?` — необязательная буква `a`, `\b` по краям — чтобы не ловить подстроки.

### 5. Негативный просмотр вперёд — «содержит, НО без ...»
```python
# Все имена, где НЕТ слов "Jr" или "Sr"
bios[bios["name"].str.contains(r"^(?!.*\b(Jr|Sr)\b).*$", na=False)]
```
`(?!...)` — «дальше НЕ должно быть …». Удобно, когда `~str.contains(...)` слишком груб.

### 6. Бонус: `str.extract` — вытащить части в отдельные колонки
Это уже не фильтр, а извлечение — но очень полезно:
```python
# Разделить "Ivanov, Ivan" на фамилию и имя
pattern = r"^(?P<surname>\w+),\s*(?P<first>\w+)$"
bios[["surname", "first"]] = bios["name"].str.extract(pattern)
```
Именованные группы `(?P<name>...)` автоматически становятся названиями колонок.

---

### Пара советов, которые сэкономят нервы:
- **`na=False`** — всегда добавляй в `str.contains`, иначе NaN в колонке даст `NaN` вместо `False`, и фильтрация сломается.
- **`case=False`** — если регистр не важен: `str.contains("anna", case=False)`.
- **`regex=True`** — дефолт в `contains`, но в `str.replace` его нужно явно указывать.
- Используй **raw-строки** `r"..."` — иначе придётся экранировать обратные слеши вдвое: `"\\d+"`.

In [43]:
bios[bios["born_country"].isin(["USA", "FRA", "GBR"]) & (bios["name"].str.startswith("Andrew"))]  # Комбинируем условия
# | - логическое ИЛИ
# .isin() - проверка столбца на наличие в нём точных совпадений с условием
# .startswith() - проверка на начало строки

,athlete_id,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date
89145,89857,Andrew Kooner,1979-03-11,Kettering,England,GBR,Canada,165.0,54.0,NaN
29915,30141,Andrew Morris,1961-11-30,Swansea,Wales,GBR,Great Britain,168.0,65.0,NaN
120710,122658,Andrew Selby,1988-12-25,Barry,Wales,GBR,Great Britain,169.0,NaN,NaN
116896,118320,Andrew Weibrecht,1986-02-10,Saranac Lake,New York,USA,United States,170.0,86.0,NaN
125429,127774,Andrew Matthews,1984-10-26,Slough,England,GBR,Great Britain,172.0,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...
62305,62768,Andrew Libano,1903-01-19,New Orleans,Louisiana,USA,United States,NaN,NaN,1935-06-22
97123,97906,Andrew Stroukoff,1950-04-27,Trenton,New Jersey,USA,United States,NaN,NaN,NaN
98703,99499,Andrew Freshwater,1973-05-31,Grantown-on-Spey,Scotland,GBR,Great Britain,NaN,NaN,NaN
139361,142832,Andrew Albicy,1990-03-21,Sèvres,Hauts-de-Seine,FRA,France,NaN,NaN,NaN
145437,149160,Andrew Blaser,1989-05-08,Meridian,Idaho,USA,United States,NaN,NaN,NaN

In [44]:
bios.query("born_country == \"USA\"")  # Ещё один способ фильтрации по условию
bios.query('born_country == "USA" and born_city == "Seattle"') # От кавычек зависит надобность в "\"

,athlete_id,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date
129572,132191,Morghan King,1985-10-08,Seattle,Washington,USA,United States,153.0,48.0,NaN
29079,29293,Joyce Tanac,1950-09-27,Seattle,Washington,USA,United States,156.0,49.0,NaN
77214,77805,Gail Devers,1966-11-19,Seattle,Washington,USA,United States,160.0,55.0,NaN
80807,81458,Cindy Kauffman,1948-08-23,Seattle,Washington,USA,United States,160.0,49.0,NaN
50802,51161,Nancy Ramey,1940-06-29,Seattle,Washington,USA,United States,160.0,51.0,NaN
...,...,...,...,...,...,...,...,...,...,...
85678,86360,"Ray Hadley, Jr.",1943-10-06,Seattle,Washington,USA,United States,NaN,NaN,1961-02-15
95265,96035,Ralf Olin,1925-04-12,Seattle,Washington,USA,Canada,NaN,NaN,2007-05-25
135448,138662,Maude Davis Crossland,2003-03-19,Seattle,Washington,USA,Colombia,NaN,NaN,NaN
136993,140229,Jenell Berhorst,2003-12-13,Seattle,Washington,USA,United States,NaN,NaN,NaN
145446,149169,Corinne Stoddard,2001-08-15,Seattle,Washington,USA,United States,NaN,NaN,NaN

In [45]:
coffee["price"] = 4.99  # Создание и заполнение нового столбца один значением

In [46]:
import numpy as np

In [47]:
coffee["new_price"] = np.where(coffee["Coffee Type"]=="Espresso", 3.99, 5.99)  # Создание нового столбца с выбором заполнения

In [48]:
coffee.drop(columns=["price"], inplace=True)  # Удаление столбца
# Используем inplace=True для автоматического изменения фрейма. Решает проблему, похожую на необходимость перезаписывать строку после изменения: text = text.replace()

In [49]:
coffee.head()

                 Day Coffee Type  Units Sold  new_price
Day
Monday        Monday    Espresso           1       3.99
Monday        Monday       Latte           1       5.99
Tuesday      Tuesday    Espresso           5       3.99
Tuesday      Tuesday       Latte           5       5.99
Wednesday  Wednesday    Espresso           5       3.99

In [50]:
coffee_new = coffee  # Неправильное копирование фрейма! Оба элемента ссылаются на один и тот же объект в памяти, из-за чего фреймы одинаковые, хотя изменения вносятся только в один фрейм
coffee_new["price"] = 4.99

coffee_new

                 Day Coffee Type  Units Sold  new_price  price
Day
Monday        Monday    Espresso           1       3.99   4.99
Monday        Monday       Latte           1       5.99   4.99
Tuesday      Tuesday    Espresso           5       3.99   4.99
Tuesday      Tuesday       Latte           5       5.99   4.99
Wednesday  Wednesday    Espresso           5       3.99   4.99
Wednesday  Wednesday       Latte           5       5.99   4.99
Thursday    Thursday    Espresso          40       3.99   4.99
Thursday    Thursday       Latte          30       5.99   4.99
Friday        Friday    Espresso          45       3.99   4.99
Friday        Friday       Latte          35       5.99   4.99
Saturday    Saturday    Espresso          45       3.99   4.99
Saturday    Saturday       Latte          35       5.99   4.99
Sunday        Sunday    Espresso          45       3.99   4.99
Sunday        Sunday       Latte          35       5.99   4.99

In [51]:
coffee

                 Day Coffee Type  Units Sold  new_price  price
Day
Monday        Monday    Espresso           1       3.99   4.99
Monday        Monday       Latte           1       5.99   4.99
Tuesday      Tuesday    Espresso           5       3.99   4.99
Tuesday      Tuesday       Latte           5       5.99   4.99
Wednesday  Wednesday    Espresso           5       3.99   4.99
Wednesday  Wednesday       Latte           5       5.99   4.99
Thursday    Thursday    Espresso          40       3.99   4.99
Thursday    Thursday       Latte          30       5.99   4.99
Friday        Friday    Espresso          45       3.99   4.99
Friday        Friday       Latte          35       5.99   4.99
Saturday    Saturday    Espresso          45       3.99   4.99
Saturday    Saturday       Latte          35       5.99   4.99
Sunday        Sunday    Espresso          45       3.99   4.99
Sunday        Sunday       Latte          35       5.99   4.99

In [52]:
coffee_new = coffee.copy()  # Правильное копирование
coffee_new["year"] = 2026

In [53]:
coffee

                 Day Coffee Type  Units Sold  new_price  price
Day
Monday        Monday    Espresso           1       3.99   4.99
Monday        Monday       Latte           1       5.99   4.99
Tuesday      Tuesday    Espresso           5       3.99   4.99
Tuesday      Tuesday       Latte           5       5.99   4.99
Wednesday  Wednesday    Espresso           5       3.99   4.99
Wednesday  Wednesday       Latte           5       5.99   4.99
Thursday    Thursday    Espresso          40       3.99   4.99
Thursday    Thursday       Latte          30       5.99   4.99
Friday        Friday    Espresso          45       3.99   4.99
Friday        Friday       Latte          35       5.99   4.99
Saturday    Saturday    Espresso          45       3.99   4.99
Saturday    Saturday       Latte          35       5.99   4.99
Sunday        Sunday    Espresso          45       3.99   4.99
Sunday        Sunday       Latte          35       5.99   4.99

In [54]:
coffee_new

                 Day Coffee Type  Units Sold  new_price  price  year
Day
Monday        Monday    Espresso           1       3.99   4.99  2026
Monday        Monday       Latte           1       5.99   4.99  2026
Tuesday      Tuesday    Espresso           5       3.99   4.99  2026
Tuesday      Tuesday       Latte           5       5.99   4.99  2026
Wednesday  Wednesday    Espresso           5       3.99   4.99  2026
Wednesday  Wednesday       Latte           5       5.99   4.99  2026
Thursday    Thursday    Espresso          40       3.99   4.99  2026
Thursday    Thursday       Latte          30       5.99   4.99  2026
Friday        Friday    Espresso          45       3.99   4.99  2026
Friday        Friday       Latte          35       5.99   4.99  2026
Saturday    Saturday    Espresso          45       3.99   4.99  2026
Saturday    Saturday       Latte          35       5.99   4.99  2026
Sunday        Sunday    Espresso          45       3.99   4.99  2026
Sunday        Sunday       Latte          35       5.99   4.99  2026

In [55]:
coffee = coffee[["Day", "Coffee Type", "Units Sold", "new_price"]]  # Ещё способ выбрать или скопировать фрейм с конкретными столбцами

In [56]:
coffee["revenue"] = coffee["Units Sold"] * coffee["new_price"]  # Добавление стобца выручки

In [57]:
coffee.rename(columns={"new_price": "price"}, inplace=True)  # Переименование столбца

In [58]:
coffee.head()

                 Day Coffee Type  Units Sold  price  revenue
Day
Monday        Monday    Espresso           1   3.99     3.99
Monday        Monday       Latte           1   5.99     5.99
Tuesday      Tuesday    Espresso           5   3.99    19.95
Tuesday      Tuesday       Latte           5   5.99    29.95
Wednesday  Wednesday    Espresso           5   3.99    19.95

In [59]:
bios_new = bios.copy()

In [60]:
bios_new["first_name"] = bios_new["name"].str.split().str[0]  # Создание нового столбца из первого слова в ячейке "name"

In [61]:
bios_new.head()

,athlete_id,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date,first_name
4515,4530,Lyton Mphande,1963-05-14,NaN,NaN,NaN,Malawi,127.0,62.0,NaN,Lyton
28619,28832,Rosario Briones,1953-10-05,San Luis Potosí,San Luis Potosí,MEX,Mexico,127.0,42.0,NaN,Rosario
4516,4531,Helman Palije,1967-06-24,NaN,NaN,NaN,Malawi,128.0,74.0,NaN,Helman
4664,4681,Salvador Miranda,1949-09-13,NaN,NaN,NaN,Nicaragua,130.0,51.0,NaN,Salvador
4517,4532,Boston Simbeye,1959-12-24,NaN,NaN,NaN,Malawi,130.0,67.0,NaN,Boston

In [62]:
bios_new.info()

<class 'pandas.DataFrame'>
Index: 145500 entries, 4515 to 145499
Data columns (total 11 columns):
 #   Column        Non-Null Count   Dtype
---  ------        --------------   -----
 0   athlete_id    145500 non-null  int64
 1   name          145500 non-null  str
 2   born_date     143693 non-null  str
 3   born_city     110908 non-null  str
 4   born_region   110908 non-null  str
 5   born_country  110908 non-null  str
 6   NOC           145499 non-null  str
 7   height_cm     106651 non-null  float64
 8   weight_kg     102070 non-null  float64
 9   died_date     33940 non-null   str
 10  first_name    145500 non-null  object
dtypes: float64(2), int64(1), object(1), str(7)
memory usage: 20.8+ MB

In [63]:
bios_new["born_datetime"] = pd.to_datetime(bios_new["born_date"])  # Создаём новый столбец и задаём ему тип данных datetime
# bios_new["born_datetime"] = pd.to_datetime(bios_new["born_date"], format="%Y-%m-%d")  # Можно явно задать формат даты
# bios_new["born_datetime"] = pd.to_datetime(bios_new["born_date"], errors="coerce")  # Преобразование данных для верной работы с форматами даты

In [64]:
bios_new.head()

,athlete_id,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date,first_name,born_datetime
4515,4530,Lyton Mphande,1963-05-14,NaN,NaN,NaN,Malawi,127.0,62.0,NaN,Lyton,1963-05-14
28619,28832,Rosario Briones,1953-10-05,San Luis Potosí,San Luis Potosí,MEX,Mexico,127.0,42.0,NaN,Rosario,1953-10-05
4516,4531,Helman Palije,1967-06-24,NaN,NaN,NaN,Malawi,128.0,74.0,NaN,Helman,1967-06-24
4664,4681,Salvador Miranda,1949-09-13,NaN,NaN,NaN,Nicaragua,130.0,51.0,NaN,Salvador,1949-09-13
4517,4532,Boston Simbeye,1959-12-24,NaN,NaN,NaN,Malawi,130.0,67.0,NaN,Boston,1959-12-24

In [65]:
bios_new.info()

<class 'pandas.DataFrame'>
Index: 145500 entries, 4515 to 145499
Data columns (total 12 columns):
 #   Column         Non-Null Count   Dtype
---  ------         --------------   -----
 0   athlete_id     145500 non-null  int64
 1   name           145500 non-null  str
 2   born_date      143693 non-null  str
 3   born_city      110908 non-null  str
 4   born_region    110908 non-null  str
 5   born_country   110908 non-null  str
 6   NOC            145499 non-null  str
 7   height_cm      106651 non-null  float64
 8   weight_kg      102070 non-null  float64
 9   died_date      33940 non-null   str
 10  first_name     145500 non-null  object
 11  born_datetime  143693 non-null  datetime64[us]
dtypes: datetime64[us](1), float64(2), int64(1), object(1), str(7)
memory usage: 21.9+ MB

In [66]:
bios_new["born_year"] = bios_new["born_datetime"].dt.year  # С помощью типа данных datetime можем обратиться к году и создать новый столбец
bios_new["is_leap_year"] = bios_new["born_datetime"].dt.is_leap_year  # Можно добавить флаг високосного года

bios_new[["name", "born_year", "is_leap_year"]]

                         name  born_year  is_leap_year
4515            Lyton Mphande     1963.0         False
28619         Rosario Briones     1953.0         False
4516            Helman Palije     1967.0         False
4664         Salvador Miranda     1949.0         False
4517           Boston Simbeye     1959.0         False
...                       ...        ...           ...
145490            Sin Ye-Chan     1995.0         False
145491          Matthew Wepke     1989.0         False
145492  Carlos García-Ordóñez     1927.0         False
145493     Landysh Falyakhova     1998.0         False
145499          Bill Phillips     1913.0         False

[145500 rows x 3 columns]

Шпаргалка по форматам даты: https://www.bairesdev.com/tools/strftime/?__cf_chl_f_tk=hwktMs.nEQyGiMJTkcXHERyFhdzfYqZlaCtUqCF7vCY-1783415293-1.0.1.1-5WStowqWwc87BhQcgYiM09fHmTGui2J8_0DAnf3NUog

In [67]:
bios_new.to_csv("data/bios_new.csv", index=False)  # Сохранение обновлённого фрейма в файл, где индексы не добавлены

In [68]:
bios["height_category"] = bios["height_cm"].apply(lambda x: "Short" if x < 165 else ("Average" if x < 185 else "Tall"))  # Использование lambda для формирования нового столбца с условием

In [69]:
bios.sample(15)

,athlete_id,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date,height_category
141418,144963,Park Eun-Jin,1999-12-15,NaN,NaN,NaN,Republic of Korea,187.0,NaN,NaN,Tall
81577,82229,Christa Rothenburger-Luding,1959-12-04,Weißwasser,Sachsen,GER,East Germany Germany,164.0,60.0,NaN,Short
38737,39040,Herman Zaanen,1948-03-15,Rotterdam,Zuid-Holland,NED,Netherlands,169.0,50.0,NaN,Average
101765,102694,Yasuyo Yamagishi,1979-11-28,NaN,NaN,NaN,Japan,163.0,62.0,NaN,Short
142907,146537,Tity Dumbuya,2003-02-21,NaN,NaN,NaN,Sierra Leone,NaN,NaN,NaN,Tall
11629,11690,Eduard Budil,1924-06-01,Wien (Vienna),Wien,AUT,Austria,180.0,80.0,2015-02-26,Average
129145,131744,Nina Christen,1994-02-07,Wolfenschiessen,Nidwalden,SUI,Switzerland,160.0,57.0,NaN,Short
37258,37554,Viola Poley,1955-04-13,Berlin,Berlin,GER,East Germany,169.0,68.0,NaN,Average
35227,35501,David Ramage,1939-06-25,Dimboola,Victoria,AUS,Australia,180.0,82.0,NaN,Average
50325,50683,Tatyana Devyatova,1948-09-19,Kupyansk,Kharkiv,UKR,Soviet Union,166.0,61.0,NaN,Average
4608,4624,Palamdorjiin Bayar,1941-05-25,NaN,NaN,NaN,Mongolia,164.0,57.0,NaN,Short
58621,59039,Takashi Kobayashi,1963-05-17,Ushiku,Ibaraki,JPN,Japan,153.0,52.0,NaN,Short
54371,54762,Pavol Dindžík,1971-04-25,Bratislava,Bratislava,SVK,Czechoslovakia,NaN,NaN,NaN,Tall
126584,128952,Madeline Hills,1987-05-15,Shellharbour,New South Wales,AUS,Australia,174.0,53.0,NaN,Average
99952,100760,Heikki Hirvonen,1895-02-08,Rääkkylä,Pohjois-Karjala,FIN,Finland,NaN,NaN,1973-08-19,Tall

In [70]:
def categorize_athlete(row):
    """Определение атлета по весу и росту."""
    if row["height_cm"] < 175 and row["weight_kg"] < 70:
        return "Lightweight"
    elif row["height_cm"] < 185 or row["weight_kg"] <= 80:
        return "Middleweight"
    else:
        return "Heavyweight"


bios["Category"] = bios.apply(categorize_athlete, axis=1)  # axis=1 - выбор между строками и столбцами (0 и 1 соответственно)

In [71]:
bios.head()

,athlete_id,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date,height_category,Category
4515,4530,Lyton Mphande,1963-05-14,NaN,NaN,NaN,Malawi,127.0,62.0,NaN,Short,Lightweight
28619,28832,Rosario Briones,1953-10-05,San Luis Potosí,San Luis Potosí,MEX,Mexico,127.0,42.0,NaN,Short,Lightweight
4516,4531,Helman Palije,1967-06-24,NaN,NaN,NaN,Malawi,128.0,74.0,NaN,Short,Middleweight
4664,4681,Salvador Miranda,1949-09-13,NaN,NaN,NaN,Nicaragua,130.0,51.0,NaN,Short,Lightweight
4517,4532,Boston Simbeye,1959-12-24,NaN,NaN,NaN,Malawi,130.0,67.0,NaN,Short,Lightweight

In [72]:
nocs = pd.read_csv("data/noc_regions.csv")

In [73]:
nocs.head()

   NOC       region                 notes
0  AFG  Afghanistan                   NaN
1  AHO      Curacao  Netherlands Antilles
2  ALB      Albania                   NaN
3  ALG      Algeria                   NaN
4  AND      Andorra                   NaN

In [74]:
bios_new = pd.merge(bios, nocs, left_on="born_country", right_on="NOC", how="left", suffixes=["_bios", "_noc"])  # Объединение таблиц
# left_on="born_country", right_on="NOC" - выбираем столбцы, по которым будем объединять фреймы из первой таблицы и второй, что в аргументах указали ранее
# how="left" - выбираем тип объединения, например, ещё есть "inner" и так далее, как в SQL запросах
# suffixes=["_bios", "_noc"] - суффиксы для названия одинаковых столбцов из разных фреймов

In [75]:
bios_new.rename(columns={"region": "born_country_full"}, inplace=True)

In [76]:
bios_new.head()

,athlete_id,name,born_date,born_city,born_region,born_country,NOC_bios,height_cm,weight_kg,died_date,height_category,Category,NOC_noc,born_country_full,notes
0,4530,Lyton Mphande,1963-05-14,NaN,NaN,NaN,Malawi,127.0,62.0,NaN,Short,Lightweight,NaN,NaN,NaN
1,28832,Rosario Briones,1953-10-05,San Luis Potosí,San Luis Potosí,MEX,Mexico,127.0,42.0,NaN,Short,Lightweight,MEX,Mexico,NaN
2,4531,Helman Palije,1967-06-24,NaN,NaN,NaN,Malawi,128.0,74.0,NaN,Short,Middleweight,NaN,NaN,NaN
3,4681,Salvador Miranda,1949-09-13,NaN,NaN,NaN,Nicaragua,130.0,51.0,NaN,Short,Lightweight,NaN,NaN,NaN
4,4532,Boston Simbeye,1959-12-24,NaN,NaN,NaN,Malawi,130.0,67.0,NaN,Short,Lightweight,NaN,NaN,NaN

In [77]:
bios_new[bios_new["NOC_bios"] != bios_new["born_country_full"]]  # Ищём записи, где страна рождения атлета не совпадает со страной, под флагом которой он выступал на Олимпийских играх

,athlete_id,name,born_date,born_city,born_region,born_country,NOC_bios,height_cm,weight_kg,died_date,height_category,Category,NOC_noc,born_country_full,notes
0,4530,Lyton Mphande,1963-05-14,NaN,NaN,NaN,Malawi,127.0,62.0,NaN,Short,Lightweight,NaN,NaN,NaN
2,4531,Helman Palije,1967-06-24,NaN,NaN,NaN,Malawi,128.0,74.0,NaN,Short,Middleweight,NaN,NaN,NaN
3,4681,Salvador Miranda,1949-09-13,NaN,NaN,NaN,Nicaragua,130.0,51.0,NaN,Short,Lightweight,NaN,NaN,NaN
4,4532,Boston Simbeye,1959-12-24,NaN,NaN,NaN,Malawi,130.0,67.0,NaN,Short,Lightweight,NaN,NaN,NaN
5,49016,Nadia Fezzani,NaN,NaN,NaN,NaN,Libya,131.0,41.0,NaN,Short,Lightweight,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
145493,149215,Shakeel John,2001-07-30,Mount Hope,Tunapuna-Piarco,TTO,Trinidad and Tobago,NaN,NaN,NaN,Tall,Heavyweight,TTO,Trinidad,Trinidad and Tobago
145494,149216,Ye Jielong,2000-03-02,NaN,NaN,NaN,People's Republic of China,NaN,NaN,NaN,Tall,Heavyweight,NaN,NaN,NaN
145495,149217,Sin Ye-Chan,1995-06-13,NaN,NaN,NaN,Republic of Korea,NaN,NaN,NaN,Tall,Heavyweight,NaN,NaN,NaN
145496,149218,Matthew Wepke,1989-12-05,NaN,NaN,NaN,Jamaica,NaN,NaN,NaN,Tall,Heavyweight,NaN,NaN,NaN
145498,149220,Landysh Falyakhova,1998-08-31,Dva Polya Artash,Respublika Tatarstan,RUS,ROC,NaN,NaN,NaN,Tall,Heavyweight,RUS,Russia,NaN

In [78]:
usa = bios[bios["born_country"] == "USA"].copy()  # Создаём новый фрейм, в котором только отлеты, родившиеся в США
gbr = bios[bios["born_country"] == "GBR"].copy()

In [79]:
usa.head()

,athlete_id,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date,height_category,Category
114670,115987,Julianne Kirchner,1991-12-19,Florence,Alabama,USA,Marshall Islands,138.0,54.0,NaN,Short,Lightweight
29088,29302,Kim Zmeskal,1976-02-06,Houston,Texas,USA,United States,139.0,36.0,NaN,Short,Lightweight
56566,56969,Joe DePietro,1914-06-10,Paterson,New Jersey,USA,United States,140.0,56.0,1999-03-19,Short,Lightweight
29077,29291,Kerri Strug,1977-11-19,Tucson,Arizona,USA,United States,142.0,37.0,NaN,Short,Lightweight
50809,51168,Aileen Riggin,1906-05-02,Newport,Rhode Island,USA,United States,142.0,NaN,2002-10-19,Short,Middleweight

In [80]:
new_df = pd.concat([usa, gbr])  # Объединяем 2 фрейма, накладывая их друг на друга в порядке записи в массиве из аргумента
# new_df = pd.concat([usa, coffee])  # Можно даже совместить несовместимое, тогда получится таблица, в которой сначала пустые значения у столбов coffee, потом - у usa

In [81]:
new_df.head()

,athlete_id,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date,height_category,Category
114670,115987,Julianne Kirchner,1991-12-19,Florence,Alabama,USA,Marshall Islands,138.0,54.0,NaN,Short,Lightweight
29088,29302,Kim Zmeskal,1976-02-06,Houston,Texas,USA,United States,139.0,36.0,NaN,Short,Lightweight
56566,56969,Joe DePietro,1914-06-10,Paterson,New Jersey,USA,United States,140.0,56.0,1999-03-19,Short,Lightweight
29077,29291,Kerri Strug,1977-11-19,Tucson,Arizona,USA,United States,142.0,37.0,NaN,Short,Lightweight
50809,51168,Aileen Riggin,1906-05-02,Newport,Rhode Island,USA,United States,142.0,NaN,2002-10-19,Short,Middleweight

In [82]:
new_df.tail()

,athlete_id,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date,height_category,Category
144760,148461,Elsa Desmond,1997-08-06,High Wycombe,England,GBR,Ireland,NaN,NaN,NaN,Tall,Heavyweight
144811,148512,Benjamin Alexander,1983-05-08,London,England,GBR,Jamaica,NaN,NaN,NaN,Tall,Heavyweight
144815,148517,Ashley Watson,1993-10-28,Peterborough,England,GBR,Jamaica,NaN,NaN,NaN,Tall,Heavyweight
145319,149041,Axel Brown,1992-04-02,Harrogate,England,GBR,Trinidad and Tobago,NaN,NaN,NaN,Tall,Heavyweight
145388,149111,Jean-Luc Baker,1993-10-07,Burnley,England,GBR,United States,NaN,NaN,NaN,Tall,Heavyweight

In [83]:
combined_df = pd.merge(results, bios, on="athlete_id", how="left")  # Объединяем 2 фрейма с общим столбцом, по типу ForeignKey из Django, из-за чего совмещать их проще и нужен только 1 параметр

In [84]:
combined_df.head()

,year,type,discipline,event,as,athlete_id,noc,team,place,tied,...,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date,height_category,Category
0,1912.0,Summer,Tennis,"Singles, Men (Olympic)",Jean-François Blanchy,1,FRA,NaN,17.0,True,...,1886-12-12,Bordeaux,Gironde,FRA,France,NaN,NaN,1960-10-02,Tall,Heavyweight
1,1912.0,Summer,Tennis,"Doubles, Men (Olympic)",Jean-François Blanchy,1,FRA,Jean Montariol,NaN,False,...,1886-12-12,Bordeaux,Gironde,FRA,France,NaN,NaN,1960-10-02,Tall,Heavyweight
2,1920.0,Summer,Tennis,"Singles, Men (Olympic)",Jean-François Blanchy,1,FRA,NaN,32.0,True,...,1886-12-12,Bordeaux,Gironde,FRA,France,NaN,NaN,1960-10-02,Tall,Heavyweight
3,1920.0,Summer,Tennis,"Doubles, Mixed (Olympic)",Jean-François Blanchy,1,FRA,Jeanne Vaussard,8.0,True,...,1886-12-12,Bordeaux,Gironde,FRA,France,NaN,NaN,1960-10-02,Tall,Heavyweight
4,1920.0,Summer,Tennis,"Doubles, Men (Olympic)",Jean-François Blanchy,1,FRA,Jacques Brugnon,4.0,False,...,1886-12-12,Bordeaux,Gironde,FRA,France,NaN,NaN,1960-10-02,Tall,Heavyweight

In [85]:
coffee = coffee.reset_index(drop=True)  # Сбрасываем индексы не пересоздавая столбец "Day"

# coffee["row_number"] = np.arange(len(coffee))  # Создание столбца с номерами строк от 0
# coffee = coffee[["row_number", "Day", "Coffee Type", "Units Sold", "price", "revenue"]]  # Меняем местами столбы. Не сработает, так как столбец "индексов": "Day" не сместится, их будет 2

In [86]:
coffee

          Day Coffee Type  Units Sold  price  revenue
0      Monday    Espresso           1   3.99     3.99
1      Monday       Latte           1   5.99     5.99
2     Tuesday    Espresso           5   3.99    19.95
3     Tuesday       Latte           5   5.99    29.95
4   Wednesday    Espresso           5   3.99    19.95
5   Wednesday       Latte           5   5.99    29.95
6    Thursday    Espresso          40   3.99   159.60
7    Thursday       Latte          30   5.99   179.70
8      Friday    Espresso          45   3.99   179.55
9      Friday       Latte          35   5.99   209.65
10   Saturday    Espresso          45   3.99   179.55
11   Saturday       Latte          35   5.99   209.65
12     Sunday    Espresso          45   3.99   179.55
13     Sunday       Latte          35   5.99   209.65

In [87]:
coffee.loc[[0, 1], "Units Sold"] = np.nan  # Записываем в 2 первые строки в поле "Units Sold" нулевые

In [88]:
coffee.isna()  # Вывод фрейма, где в ячейках True или False в зависимости нуливое ли там значения

      Day  Coffee Type  Units Sold  price  revenue
0   False        False        True  False    False
1   False        False        True  False    False
2   False        False       False  False    False
3   False        False       False  False    False
4   False        False       False  False    False
5   False        False       False  False    False
6   False        False       False  False    False
7   False        False       False  False    False
8   False        False       False  False    False
9   False        False       False  False    False
10  False        False       False  False    False
11  False        False       False  False    False
12  False        False       False  False    False
13  False        False       False  False    False

In [89]:
coffee.isna().sum()  # Сумма нулевых значений для каждого столбца

Day            0
Coffee Type    0
Units Sold     2
price          0
revenue        0
dtype: int64

In [90]:
# coffee.fillna(1000)  # Заполнение ячеек с нулями собственным значением
# coffee["Units Sold"].interpolate()  # Интерполяция - функция заполнения значений, словно 1, 2 и так далее в Excel
# В данном случае интерполяция не заполнит значения, так как не понятно, как заполнять первые записи из-за отсутствия предшествующий значений и системы в последующих
coffee.fillna(coffee["Units Sold"].mean())  # Заполнение нулей средним по столбцу значением

          Day Coffee Type  Units Sold  price  revenue
0      Monday    Espresso        27.5   3.99     3.99
1      Monday       Latte        27.5   5.99     5.99
2     Tuesday    Espresso         5.0   3.99    19.95
3     Tuesday       Latte         5.0   5.99    29.95
4   Wednesday    Espresso         5.0   3.99    19.95
5   Wednesday       Latte         5.0   5.99    29.95
6    Thursday    Espresso        40.0   3.99   159.60
7    Thursday       Latte        30.0   5.99   179.70
8      Friday    Espresso        45.0   3.99   179.55
9      Friday       Latte        35.0   5.99   209.65
10   Saturday    Espresso        45.0   3.99   179.55
11   Saturday       Latte        35.0   5.99   209.65
12     Sunday    Espresso        45.0   3.99   179.55
13     Sunday       Latte        35.0   5.99   209.65

In [91]:
# Изменение значений для работающей интерполяции
coffee.loc[[2, 3], "Units Sold"] = np.nan
coffee.loc[[0, 1], "Units Sold"] = 15
coffee.loc[[4, 5], "Units Sold"] = 30

In [92]:
coffee["Units Sold"] = coffee["Units Sold"].interpolate()

In [93]:
coffee

          Day Coffee Type  Units Sold  price  revenue
0      Monday    Espresso        15.0   3.99     3.99
1      Monday       Latte        15.0   5.99     5.99
2     Tuesday    Espresso        20.0   3.99    19.95
3     Tuesday       Latte        25.0   5.99    29.95
4   Wednesday    Espresso        30.0   3.99    19.95
5   Wednesday       Latte        30.0   5.99    29.95
6    Thursday    Espresso        40.0   3.99   159.60
7    Thursday       Latte        30.0   5.99   179.70
8      Friday    Espresso        45.0   3.99   179.55
9      Friday       Latte        35.0   5.99   209.65
10   Saturday    Espresso        45.0   3.99   179.55
11   Saturday       Latte        35.0   5.99   209.65
12     Sunday    Espresso        45.0   3.99   179.55
13     Sunday       Latte        35.0   5.99   209.65

In [94]:
coffee.loc[[2, 3], "Units Sold"] = np.nan

In [ ]:
coffee.dropna(inplace=True)  # Удаление записей с нулями
# coffee.dropna(subset=["Units Sold"], inplace=True)  #  subset="Units Sold" - подстановка столбцов, в которых нужно удалить записи. В данном случае работает и без этого параметра
# Например, в другом случае можно будет заменять значения, а не удалять их. Если без этого параметра, то удалятся все записи, где есть хотя бы один нулевой элемент в любом столбце.

In [96]:
coffee

          Day Coffee Type  Units Sold  price  revenue
0      Monday    Espresso        15.0   3.99     3.99
1      Monday       Latte        15.0   5.99     5.99
4   Wednesday    Espresso        30.0   3.99    19.95
5   Wednesday       Latte        30.0   5.99    29.95
6    Thursday    Espresso        40.0   3.99   159.60
7    Thursday       Latte        30.0   5.99   179.70
8      Friday    Espresso        45.0   3.99   179.55
9      Friday       Latte        35.0   5.99   209.65
10   Saturday    Espresso        45.0   3.99   179.55
11   Saturday       Latte        35.0   5.99   209.65
12     Sunday    Espresso        45.0   3.99   179.55
13     Sunday       Latte        35.0   5.99   209.65

In [97]:
coffee.loc[[7, 8], "Units Sold"] = np.nan

In [98]:
coffee[coffee["Units Sold"].isna()]  # Вывод записей с нулевыми значениями в конкретном столбце

        Day Coffee Type  Units Sold  price  revenue
7  Thursday       Latte         NaN   5.99   179.70
8    Friday    Espresso         NaN   3.99   179.55

In [99]:
coffee[coffee["Units Sold"].notna()]  # Вывод записей без нулевых значений в конкретном столбце

          Day Coffee Type  Units Sold  price  revenue
0      Monday    Espresso        15.0   3.99     3.99
1      Monday       Latte        15.0   5.99     5.99
4   Wednesday    Espresso        30.0   3.99    19.95
5   Wednesday       Latte        30.0   5.99    29.95
6    Thursday    Espresso        40.0   3.99   159.60
9      Friday       Latte        35.0   5.99   209.65
10   Saturday    Espresso        45.0   3.99   179.55
11   Saturday       Latte        35.0   5.99   209.65
12     Sunday    Espresso        45.0   3.99   179.55
13     Sunday       Latte        35.0   5.99   209.65

In [100]:
bios["born_city"].value_counts()  # Вывод количества записей по ключам конкретного столбца по убыванию

born_city
Budapest            1378
Moskva (Moscow)      883
Oslo                 708
Stockholm            629
Praha (Prague)       600
                    ...
Scandiano              1
Tsivilsk               1
Roth                   1
Dva Polya Artash       1
Dulwich Hill           1
Name: count, Length: 22368, dtype: int64

In [101]:
bios[bios["born_country"] == "USA"]["born_city"].value_counts().head()  # Комбинирование условий и вывод городов США. Можно и без .head()

born_city
New York        416
Chicago         283
Los Angeles     230
Philadelphia    205
Boston          153
Name: count, dtype: int64

In [102]:
coffee.groupby(["Coffee Type"])["Units Sold"].sum()  # Вывод суммы всех проданных единиц кофе по типам
coffee.groupby(["Coffee Type"])["Units Sold"].mean()  # Вывод среднего по всем проданным единицам кофе по типам

Coffee Type
Espresso    35.0
Latte       30.0
Name: Units Sold, dtype: float64

In [103]:
coffee.groupby(["Coffee Type"]).agg({"Units Sold": "sum", "price": "mean"})  # Сводка из двух столбов из количества проданных типов кофе по сумме всех проданных и стоимости по среднему

             Units Sold  price
Coffee Type
Espresso          175.0   3.99
Latte             150.0   5.99

In [104]:
coffee.groupby(["Coffee Type", "Day"]).agg({"Units Sold": "sum", "price": "mean"})  # Можно выводить больше столбцов

                       Units Sold  price
Coffee Type Day
Espresso    Friday            0.0   3.99
            Monday           15.0   3.99
            Saturday         45.0   3.99
            Sunday           45.0   3.99
            Thursday         40.0   3.99
            Wednesday        30.0   3.99
Latte       Friday           35.0   5.99
            Monday           15.0   5.99
            Saturday         35.0   5.99
            Sunday           35.0   5.99
            Thursday          0.0   5.99
            Wednesday        30.0   5.99

In [105]:
pivot = coffee.pivot(columns="Coffee Type", index="Day", values="revenue")  # Сводная таблица с отдельными столбцами

In [106]:
pivot

Coffee Type  Espresso   Latte
Day
Friday         179.55  209.65
Monday           3.99    5.99
Saturday       179.55  209.65
Sunday         179.55  209.65
Thursday       159.60  179.70
Wednesday       19.95   29.95

In [107]:
# С помощью сводной таблицы легче найти подобные значения
pivot.loc["Friday", "Espresso"]
pivot.sum()  # Суммарная выручка

Coffee Type
Espresso    722.19
Latte       844.59
dtype: float64

In [108]:
pivot.sum(axis=1)  # Суммарная выручка по дням

Day
Friday       389.20
Monday         9.98
Saturday     389.20
Sunday       389.20
Thursday     339.30
Wednesday     49.90
dtype: float64

In [109]:
bios["born_date"] = pd.to_datetime(bios["born_date"])

bios["born_date"].dt.year.count()  # Количество всех записей

np.int64(143693)

In [110]:
bios.groupby(bios["born_date"].dt.year).count()

,athlete_id,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date,height_category,Category
born_date,,,,,,,,,,,,
1828.0,1,1,1,1,1,1,1,0,0,1,1,1
1831.0,2,2,2,2,2,2,2,0,0,2,2,2
1833.0,1,1,1,1,1,1,1,0,0,1,1,1
1836.0,1,1,1,1,1,1,1,0,0,1,1,1
1837.0,1,1,1,1,1,1,1,0,0,1,1,1
...,...,...,...,...,...,...,...,...,...,...,...,...
2005.0,163,163,163,64,64,64,163,13,12,1,163,163
2006.0,17,17,17,8,8,8,17,1,0,0,17,17
2007.0,3,3,3,1,1,1,3,0,0,0,3,3
2008.0,3,3,3,2,2,2,3,1,1,0,3,3
2009.0,1,1,1,1,1,1,1,0,0,0,1,1

In [111]:
bios.groupby(bios["born_date"].dt.year)["name"].count()  # Более наглядный вариант - год и количество атлетов, родившихся в него

born_date
1828.0      1
1831.0      2
1833.0      1
1836.0      1
1837.0      1
         ...
2005.0    163
2006.0     17
2007.0      3
2008.0      3
2009.0      1
Name: name, Length: 177, dtype: int64

In [112]:
bios.groupby(bios["born_date"].dt.year)["name"].count().reset_index()  # Сбрасываем индекс, так как в получившейся таблице столбец индексов - года рождения

     born_date  name
0       1828.0     1
1       1831.0     2
2       1833.0     1
3       1836.0     1
4       1837.0     1
..         ...   ...
172     2005.0   163
173     2006.0    17
174     2007.0     3
175     2008.0     3
176     2009.0     1

[177 rows x 2 columns]

In [113]:
bios.groupby(bios["born_date"].dt.year)["name"].count().reset_index().sort_values("name", ascending=False)

     born_date  name
139     1972.0  2231
152     1985.0  2227
140     1973.0  2216
138     1971.0  2205
137     1970.0  2174
..         ...   ...
4       1837.0     1
2       1833.0     1
6       1839.0     1
12      1845.0     1
176     2009.0     1

[177 rows x 2 columns]

In [114]:
bios["born_year"] = bios["born_date"].dt.year
bios["born_month"] = bios["born_date"].dt.month
bios.groupby([bios["born_year"], bios["born_month"]])["name"].count().reset_index().sort_values("name", ascending=False)  # Сортировка ещё и по месяцу рождения, где 1 - январь

      born_year  born_month  name
1437     1970.0         1.0   239
1461     1972.0         1.0   229
1497     1975.0         1.0   227
1629     1986.0         1.0   227
1617     1985.0         1.0   225
...         ...         ...   ...
1877     2006.0        12.0     1
1871     2006.0         3.0     1
20       1846.0         7.0     1
21       1846.0         8.0     1
22       1846.0         9.0     1

[1885 rows x 3 columns]

Больше функций сортировки: `.shift()`, `.rank()`, `.rolling()`, `.cumsum()`

In [115]:
coffee["yesterday_revenue"] = coffee["revenue"].shift(2)  # Новый столбец "вчерашней выручки", значения которого равны "выручке" со сдвигом 2. Сдвиг может быть отрицательным

In [116]:
coffee["pct_change"] = coffee["revenue"] / coffee["yesterday_revenue"] * 100  # Увеличение выручки в процентах

In [117]:
coffee

,Day,Coffee Type,Units Sold,price,revenue,yesterday_revenue,pct_change
0,Monday,Espresso,15.0,3.99,3.99,NaN,NaN
1,Monday,Latte,15.0,5.99,5.99,NaN,NaN
4,Wednesday,Espresso,30.0,3.99,19.95,3.99,500.000000
5,Wednesday,Latte,30.0,5.99,29.95,5.99,500.000000
6,Thursday,Espresso,40.0,3.99,159.60,19.95,800.000000
7,Thursday,Latte,NaN,5.99,179.70,29.95,600.000000
8,Friday,Espresso,NaN,3.99,179.55,159.60,112.500000
9,Friday,Latte,35.0,5.99,209.65,179.70,116.666667
10,Saturday,Espresso,45.0,3.99,179.55,179.55,100.000000
11,Saturday,Latte,35.0,5.99,209.65,209.65,100.000000
12,Sunday,Espresso,45.0,3.99,179.55,179.55,100.000000
13,Sunday,Latte,35.0,5.99,209.65,209.65,100.000000

In [118]:
bios["height_rank"] = bios["height_cm"].rank()  # Добавляем ранг спортсменов по росту

In [119]:
bios.sort_values("height_rank", ascending=False)

,athlete_id,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date,height_category,Category,born_year,born_month,height_rank
89070,89782,Yao Ming,1980-09-12,Xuhui District,Shanghai,CHN,People's Republic of China,226.0,141.0,NaN,Tall,Heavyweight,1980.0,9.0,106651.0
5781,5804,Tommy Burleson,1952-02-24,Crossnore,North Carolina,USA,United States,223.0,102.0,NaN,Tall,Heavyweight,1952.0,2.0,106649.5
6978,7013,Arvydas Sabonis,1964-12-19,Kaunas,Kaunas,LTU,Lithuania Soviet Union,223.0,122.0,NaN,Tall,Heavyweight,1964.0,12.0,106649.5
120266,122147,Zhang Zhaoxu,1987-11-18,Binzhou,Shandong,CHN,People's Republic of China,221.0,110.0,NaN,Tall,Heavyweight,1987.0,11.0,106647.0
89075,89787,Roberto Dueñas,1975-11-01,Madrid,Madrid,ESP,Spain,221.0,137.0,NaN,Tall,Heavyweight,1975.0,11.0,106647.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
145490,149217,Sin Ye-Chan,1995-06-13,NaN,NaN,NaN,Republic of Korea,NaN,NaN,NaN,Tall,Heavyweight,1995.0,6.0,NaN
145491,149218,Matthew Wepke,1989-12-05,NaN,NaN,NaN,Jamaica,NaN,NaN,NaN,Tall,Heavyweight,1989.0,12.0,NaN
145492,149219,Carlos García-Ordóñez,1927-04-24,La Habana (Havana),Ciudad de La Habana,CUB,Cuba,NaN,NaN,2019-11-24,Tall,Heavyweight,1927.0,4.0,NaN
145493,149220,Landysh Falyakhova,1998-08-31,Dva Polya Artash,Respublika Tatarstan,RUS,ROC,NaN,NaN,NaN,Tall,Heavyweight,1998.0,8.0,NaN
145499,149814,Bill Phillips,1913-07-15,Dulwich Hill,New South Wales,AUS,Australia,NaN,NaN,2003-10-20,Tall,Heavyweight,1913.0,7.0,NaN

In [120]:
bios["height_rank"] = bios["height_cm"].rank(ascending=False)  # Рейтинг спорсменов по росту, где самый высокий имеет рейтинг 1

In [121]:
bios.sort_values("height_rank")

,athlete_id,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date,height_category,Category,born_year,born_month,height_rank
89070,89782,Yao Ming,1980-09-12,Xuhui District,Shanghai,CHN,People's Republic of China,226.0,141.0,NaN,Tall,Heavyweight,1980.0,9.0,1.0
6978,7013,Arvydas Sabonis,1964-12-19,Kaunas,Kaunas,LTU,Lithuania Soviet Union,223.0,122.0,NaN,Tall,Heavyweight,1964.0,12.0,2.5
5781,5804,Tommy Burleson,1952-02-24,Crossnore,North Carolina,USA,United States,223.0,102.0,NaN,Tall,Heavyweight,1952.0,2.0,2.5
5673,5696,Gunther Behnke,1963-01-19,Leverkusen,Nordrhein-Westfalen,GER,Germany,221.0,114.0,NaN,Tall,Heavyweight,1963.0,1.0,5.0
120266,122147,Zhang Zhaoxu,1987-11-18,Binzhou,Shandong,CHN,People's Republic of China,221.0,110.0,NaN,Tall,Heavyweight,1987.0,11.0,5.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
145490,149217,Sin Ye-Chan,1995-06-13,NaN,NaN,NaN,Republic of Korea,NaN,NaN,NaN,Tall,Heavyweight,1995.0,6.0,NaN
145491,149218,Matthew Wepke,1989-12-05,NaN,NaN,NaN,Jamaica,NaN,NaN,NaN,Tall,Heavyweight,1989.0,12.0,NaN
145492,149219,Carlos García-Ordóñez,1927-04-24,La Habana (Havana),Ciudad de La Habana,CUB,Cuba,NaN,NaN,2019-11-24,Tall,Heavyweight,1927.0,4.0,NaN
145493,149220,Landysh Falyakhova,1998-08-31,Dva Polya Artash,Respublika Tatarstan,RUS,ROC,NaN,NaN,NaN,Tall,Heavyweight,1998.0,8.0,NaN
145499,149814,Bill Phillips,1913-07-15,Dulwich Hill,New South Wales,AUS,Australia,NaN,NaN,2003-10-20,Tall,Heavyweight,1913.0,7.0,NaN

In [122]:
coffee.cumsum()

,Day,Coffee Type,Units Sold,price,revenue,yesterday_revenue,pct_change
0,Monday,Espresso,15.0,3.99,3.99,NaN,NaN
1,MondayMonday,EspressoLatte,30.0,9.98,9.98,NaN,NaN
4,MondayMondayWednesday,EspressoLatteEspresso,60.0,13.97,29.93,3.99,500.000000
5,MondayMondayWednesdayWednesday,EspressoLatteEspressoLatte,90.0,19.96,59.88,9.98,1000.000000
6,MondayMondayWednesdayWednesdayThursday,EspressoLatteEspressoLatteEspresso,130.0,23.95,219.48,29.93,1800.000000
7,MondayMondayWednesdayWednesdayThursdayThursday,EspressoLatteEspressoLatteEspressoLatte,NaN,29.94,399.18,59.88,2400.000000
8,MondayMondayWednesdayWednesdayThursdayThursday...,EspressoLatteEspressoLatteEspressoLatteEspresso,NaN,33.93,578.73,219.48,2512.500000
9,MondayMondayWednesdayWednesdayThursdayThursday...,EspressoLatteEspressoLatteEspressoLatteEspress...,165.0,39.92,788.38,399.18,2629.166667
10,MondayMondayWednesdayWednesdayThursdayThursday...,EspressoLatteEspressoLatteEspressoLatteEspress...,210.0,43.91,967.93,578.73,2729.166667
11,MondayMondayWednesdayWednesdayThursdayThursday...,EspressoLatteEspressoLatteEspressoLatteEspress...,245.0,49.90,1177.58,788.38,2829.166667
12,MondayMondayWednesdayWednesdayThursdayThursday...,EspressoLatteEspressoLatteEspressoLatteEspress...,290.0,53.89,1357.13,967.93,2929.166667
13,MondayMondayWednesdayWednesdayThursdayThursday...,EspressoLatteEspressoLatteEspressoLatteEspress...,325.0,59.88,1566.78,1177.58,3029.166667

In [123]:
coffee.select_dtypes("float").cumsum()

    Units Sold  price  revenue  yesterday_revenue   pct_change
0         15.0   3.99     3.99                NaN          NaN
1         30.0   9.98     9.98                NaN          NaN
4         60.0  13.97    29.93               3.99   500.000000
5         90.0  19.96    59.88               9.98  1000.000000
6        130.0  23.95   219.48              29.93  1800.000000
7          NaN  29.94   399.18              59.88  2400.000000
8          NaN  33.93   578.73             219.48  2512.500000
9        165.0  39.92   788.38             399.18  2629.166667
10       210.0  43.91   967.93             578.73  2729.166667
11       245.0  49.90  1177.58             788.38  2829.166667
12       290.0  53.89  1357.13             967.93  2929.166667
13       325.0  59.88  1566.78            1177.58  3029.166667

In [124]:
coffee["cumulative_revenue"] = coffee["revenue"].cumsum()  # Добавляем столбец с накапливающейся суммой выручки с каждой строкой

In [125]:
coffee

,Day,Coffee Type,Units Sold,price,revenue,yesterday_revenue,pct_change,cumulative_revenue
0,Monday,Espresso,15.0,3.99,3.99,NaN,NaN,3.99
1,Monday,Latte,15.0,5.99,5.99,NaN,NaN,9.98
4,Wednesday,Espresso,30.0,3.99,19.95,3.99,500.000000,29.93
5,Wednesday,Latte,30.0,5.99,29.95,5.99,500.000000,59.88
6,Thursday,Espresso,40.0,3.99,159.60,19.95,800.000000,219.48
7,Thursday,Latte,NaN,5.99,179.70,29.95,600.000000,399.18
8,Friday,Espresso,NaN,3.99,179.55,159.60,112.500000,578.73
9,Friday,Latte,35.0,5.99,209.65,179.70,116.666667,788.38
10,Saturday,Espresso,45.0,3.99,179.55,179.55,100.000000,967.93
11,Saturday,Latte,35.0,5.99,209.65,209.65,100.000000,1177.58
12,Sunday,Espresso,45.0,3.99,179.55,179.55,100.000000,1357.13
13,Sunday,Latte,35.0,5.99,209.65,209.65,100.000000,1566.78

In [126]:
latte = coffee[coffee["Coffee Type"] == "Latte"].copy()
latte["3day"] = latte["revenue"].rolling(3).sum()  # Столбец из выручки за 3 предыдущих дня

In [127]:
latte

,Day,Coffee Type,Units Sold,price,revenue,yesterday_revenue,pct_change,cumulative_revenue,3day
1,Monday,Latte,15.0,5.99,5.99,NaN,NaN,9.98,NaN
5,Wednesday,Latte,30.0,5.99,29.95,5.99,500.000000,59.88,NaN
7,Thursday,Latte,NaN,5.99,179.70,29.95,600.000000,399.18,215.64
9,Friday,Latte,35.0,5.99,209.65,179.70,116.666667,788.38,419.30
11,Saturday,Latte,35.0,5.99,209.65,209.65,100.000000,1177.58,599.00
13,Sunday,Latte,35.0,5.99,209.65,209.65,100.000000,1566.78,628.95

### Часть 3. **Новые возможности из новодобавленного отрывка видео в гайде**

In [128]:
pd.__version__  # Узнаём версию pandas

'3.0.3'

In [129]:
results_numpy = pd.read_csv("data/results.csv")
results_arrow = pd.read_csv("data/results.csv", engine="pyarrow", dtype_backend="pyarrow")

In [130]:
results_numpy.info()

<class 'pandas.DataFrame'>
RangeIndex: 308408 entries, 0 to 308407
Data columns (total 11 columns):
 #   Column      Non-Null Count   Dtype
---  ------      --------------   -----
 0   year        305807 non-null  float64
 1   type        305807 non-null  str
 2   discipline  308407 non-null  str
 3   event       308408 non-null  str
 4   as          308408 non-null  str
 5   athlete_id  308408 non-null  int64
 6   noc         308407 non-null  str
 7   team        121714 non-null  str
 8   place       283193 non-null  float64
 9   tied        308408 non-null  bool
 10  medal       44139 non-null   str
dtypes: bool(1), float64(2), int64(1), str(7)
memory usage: 46.0 MB

In [131]:
results_arrow.info()  # Фрейм с оптимизированными строковыми типами данных

<class 'pandas.DataFrame'>
RangeIndex: 308408 entries, 0 to 308407
Data columns (total 11 columns):
 #   Column      Non-Null Count   Dtype
---  ------      --------------   -----
 0   year        305807 non-null  double[pyarrow]
 1   type        305807 non-null  string[pyarrow]
 2   discipline  308407 non-null  string[pyarrow]
 3   event       308408 non-null  string[pyarrow]
 4   as          308408 non-null  string[pyarrow]
 5   athlete_id  308408 non-null  int64[pyarrow]
 6   noc         308407 non-null  string[pyarrow]
 7   team        121714 non-null  string[pyarrow]
 8   place       283193 non-null  double[pyarrow]
 9   tied        308408 non-null  bool[pyarrow]
 10  medal       44139 non-null   string[pyarrow]
dtypes: bool[pyarrow](1), double[pyarrow](2), int64[pyarrow](1), string[pyarrow](7)
memory usage: 37.5 MB

In [132]:
results_numpy["as"].str.contains("Yana")
results_arrow["as"].str.contains("Yana")

0         False
1         False
2         False
3         False
4         False
          ...
308403    False
308404    False
308405    False
308406    False
308407    False
Name: as, Length: 308408, dtype: bool[pyarrow]

Участок кода с использованием сводной таблицы и функции для расчёта значений: `new_df = pd.pivot(df, columns="Name1", index="Name2", values="Name3", aggfunc="sum")`